### ISSUE TITLE
[BUG] Use logstash for consumption, offset submission will not be submitted after a period of time normally, restarting logstash is useless

### ISSUE THREAD

**Issue by zcola** [streamnative/kop#1041]
**Describe the bug**
Use logstash for consumption, offset submission will not be submitted after a period of time normally, restarting logstash is useless

**To Reproduce**
logstash 7.15.2

config file 
```
input {
    kafka {
        bootstrap_servers => "iowa.brokerXXXom:9092"
        group_id => "logstash_zcola_cld_dnode_kubelet_log_2020090401"
        topics => "iowa_cld_dnode_kubelet_log"
        codec => plain
        consumer_threads => 2  # number (optional)， default: 1
    }
}
output {
  stdout {
        #codec => dots
       # codec => rubydebug
    }
}
```

run command  logstash -f /etc/logstash/zcola_cld_dnode_kubelet_log --log.level debug

When I ran it yesterday, I observed that the offset was submitted normally. Today, I saw that CURRENT-OFFSET has not changed. Restarting logstash is invalid. The latest data is consumed by the same group.

pulsar 2.9.1 and pulsar-protocol-handler-kafka-2.9.1.1.nar

We have been using logstash for a few years and have been updating with the official version. There are basically no problems with kafka. The implementation uses the official kafka client.

**Comment by zcola** [comment]
./kafka-consumer-groups.sh --bootstrap-server iowa.broxxx.com:9092 --describe --group logstash_zcola_cld_dnode_kubelet_log_2020090401

TOPIC                      PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                     HOST                 CLIENT-ID
iowa_cld_dnode_kubelet_log 5          1894912089      2077863243      182951154       logstash-0-35fccd5d-aa13-49d8-9be8-21d50f2a4258 /7.32.18.20:35330    logstash-0
iowa_cld_dnode_kubelet_log 12         1685329108      2078466635      393137527       logstash-0-5b8657f9-c9ac-47d0-9178-5cef2426446f /10.191.66.218:60418 logstash-0
iowa_cld_dnode_kubelet_log 8          1870831697      2007363066      136531369       logstash-0-47aafeca-4580-4eb8-8a99-faa5532fdf7d /10.191.72.151:33870 logstash-0
iowa_cld_dnode_kubelet_log 17         1900463487      2065098749      164635262       logstash-0-709c361a-80e1-4278-8189-1d90217bf063 /10.191.71.183:43300 logstash-0
iowa_cld_dnode_kubelet_log 20         997842046       1026750884      28908838        logstash-0-8df5b8b2-d6bc-4b1b-a097-0d461d42d343 /10.191.73.228:47006 logstash-0
iowa_cld_dnode_kubelet_log 24         999426184       1028463515      29037331        logstash-0-a342d6e4-cda4-4842-bb1b-80124e415a51 /10.191.72.198:39386 logstash-0
iowa_cld_dnode_kubelet_log 27         1802456677      1982384991      179928314       logstash-0-a8d766ff-ddf0-48c7-a538-5fcc3d83c715 /7.32.21.141:57674   logstash-0
iowa_cld_dnode_kubelet_log 26         1608550625      2010130304      401579679       logstash-0-a7ad495b-035d-4836-b063-6f2fe9c5fb07 /10.192.0.137:42496  logstash-0
iowa_cld_dnode_kubelet_log 18         1001169678      1030254584      29084906        logstash-0-82868af7-88db-49cc-a4eb-9f4290fca02c /10.192.0.96:40494   logstash-0
iowa_cld_dnode_kubelet_log 2          1858871941      2035878650      177006709       logstash-0-2305b37a-71b2-4b7b-8245-06f07ee8c66d /7.32.18.21:58478    logstash-0
iowa_cld_dnode_kubelet_log 3          1898888419      2079295140      180406721       logstash-0-27526add-0b14-4c14-b358-0cc19b9c49bb /7.32.21.146:38598   logstash-0
iowa_cld_dnode_kubelet_log 13         1718934452      2069908161      350973709       logstash-0-5f168792-6fa5-468a-9065-b20c01d11a08 /7.32.21.137:55476   logstash-0
iowa_cld_dnode_kubelet_log 16         1898481237      2079987716      181506479       logstash-0-6e9a9784-1ce7-4b9e-ab64-352a438aa12f /10.191.66.202:49358 logstash-0
iowa_cld_dnode_kubelet_log 29         880006579       915884433       35877854        logstash-0-bc4ae607-bd65-4e5b-b8b8-2a743c8fc9f2 /10.191.66.215:55514 logstash-0
iowa_cld_dnode_kubelet_log 14         999642971       1028644579      29001608        logstash-0-60482a82-c410-4373-9f2b-ee7324c61692 /10.191.72.221:43978 logstash-0
iowa_cld_dnode_kubelet_log 9          1933120254      2073872547      140752293       logstash-0-512ce919-d6fe-43c8-83d4-0ce2dccfc7af /10.191.72.189:36980 logstash-0
iowa_cld_dnode_kubelet_log 21         929831710       965654627       35822917        logstash-0-92275b55-09d6-4d90-a16d-0259eb06a25c /10.191.66.213:50142 logstash-0
iowa_cld_dnode_kubelet_log 0          1678555665      2043359502      364803837       logstash-0-00f1b971-bc07-4c13-ab08-1248b172c841 /10.191.72.154:47452 logstash-0
iowa_cld_dnode_kubelet_log 7          1911703726      2076260776      164557050       logstash-0-45a1dfd0-d4e4-4487-9a37-8129e81ec023 /10.191.66.203:52468 logstash-0
iowa_cld_dnode_kubelet_log 11         961639418       997258840       35619422        logstash-0-5431ec25-4f0d-48ad-936f-dabb979e1bd0 /10.192.0.74:49426   logstash-0
iowa_cld_dnode_kubelet_log 28         1000985318      1030109822      29124504        logstash-0-aa7b6ac9-333f-4223-aa48-002ca3c80768 /10.191.71.182:59786 logstash-0
iowa_cld_dnode_kubelet_log 23         1807747211      1989064672      181317461       logstash-0-97db8003-32bc-44e3-be31-b994cdc5e590 /7.32.21.140:34676   logstash-0
iowa_cld_dnode_kubelet_log 15         961922510       997656748       35734238        logstash-0-6158e45f-f15d-43ea-b104-edc8e8ef0478 /10.191.66.206:53644 logstash-0
iowa_cld_dnode_kubelet_log 19         961547123       997301663       35754540        logstash-0-82a7c0cb-c7ab-4d37-af8a-f37ff7dd2149 /10.192.0.5:54496    logstash-0
iowa_cld_dnode_kubelet_log 10         997440390       1026271876      28831486        logstash-0-528bb45a-b9a4-4ab3-971e-2a8372047b86 /10.192.0.138:53946  logstash-0
iowa_cld_dnode_kubelet_log 6          1844642708      2020275531      175632823       logstash-0-4398a05a-e4eb-4206-94c4-e89ff70e6af9 /7.32.21.148:43198   logstash-0
iowa_cld_dnode_kubelet_log 4          1861384436      2028223446      166839010       logstash-0-33026973-9671-4fc8-bee1-0cb0af476ab1 /10.192.0.130:35348  logstash-0
iowa_cld_dnode_kubelet_log 22         1865551418      2010627492      145076074       logstash-0-9253b623-accf-44c9-aba3-546b6271c0ee /10.191.72.25:32966  logstash-0
iowa_cld_dnode_kubelet_log 25         881166887       917062508       35895621        logstash-0-a4347767-effd-4337-8df8-7e8a2dd520aa /10.192.0.7:53832    logstash-0
iowa_cld_dnode_kubelet_log 1          1931854812      2079855475      148000663       logstash-0-08319085-d0fa-4381-a3a2-561241179193 /10.191.72.153:57738 logstash-0

**Comment by zcola** [comment]
[broker.log](https://github.com/streamnative/kop/files/7950981/broker.log)

**Comment by zcola** [comment]
[dump.log](https://github.com/streamnative/kop/files/8039729/dump.log)

**Comment by Demogorgon314** [comment]
What version of kafka admin are you using? Can you provide the command you used? Thanks.

**Comment by zcola** [comment]
> What version of kafka admin are you using? Can you provide the command you used? Thanks.

2.0.0 and 3.1.0 are the same

**Comment by BewareMyPower** [comment]
After killing 3 of 4 all brokers, the offset commit works. It looks like there is something wrong with the read/write on the system topic `public/__kafka/__consumer_offsets`.

We need to review the existing code again to look into this problem.

**Comment by SunDapeng1** [comment]
How is the issue going ？ We have the same problem：
    logstash 7.10.0
    kop：2.9.3.2
    pulsar：2.9.3
There is no problem with a new consumer group， but offset submission will not be submitted after a period of time normally. 
And the same  with kafka client this time. 
what's more, we have this in kop.log, I'm not sure whether it is related
![image](https://user-images.githubusercontent.com/42792537/226231801-93ad2af0-595e-460e-81ef-1959d0ce4c00.png)

**Comment by zcola** [comment]
https://github.com/streamnative/kop/pull/1501

fixed
