### ISSUE TITLE
[BUG] serializeResponse failed at AbstractResponse.toStruct(version)  but without any exception thrown

### ISSUE THREAD

**Issue by lujiwen** [streamnative/kop#1059]
**Describe the bug**
when kafka client sends request to kop for API version, before kop send response back to client, it failed to serialize Response at method call `response.toStruct(version)` and request close, without any exception been thrown, no clue for me to figure this out.

**To Reproduce**
1. Setup pulsar broker with kop
2. try to produce message to broker  
3. the client debug log tells that the client was fetching API version, but could not get corresponding response 
4. timeout and disconnected (timeout = 60s) 

client log 
2022-02-09 14:50:43:425 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Completed connection to node -1. Fetching API versions.
2022-02-09 14:50:43:425 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Initiating API versions fetch from node -1.
2022-02-09 14:51:13:434 [kafka-producer-network-thread | producer-1] DEBUG org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Disconnecting from node -1 due to request timeout.

**Expected behavior**
client succeed to get api version and metadata, then produce message to pulsar successfully

**Additional context**
kafka client version : 2.6.0
kop version: 2.9.1.4
pulsar version: 2.9.1
JRE: OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
linux: Linux version 5.10.26-20

**Comment by BewareMyPower** [comment]
Could you upload the broker's log (debug level)?

**Comment by BewareMyPower** [comment]
It's better to try to reproduce the bug with standalone mode, and give more details. Then we can try to reproduce it locally.

For example,
1. Run KoP standalone with following configs.
  ```properties
  kkk=vvv
  # ...
  ```
2. Run Kafka 2.6.0 command line tool:
  ```bash
   # ...
  ```  
3. Upload the standalone logs.

**Comment by lujiwen** [comment]
@BewareMyPower I have figured out the reason why this happened. A few days ago, to enable log4j2(pulsar broker) connecting Kafka topic for logging purpose, I put a kafka-clients-2.0.0.jar into pulsar/lib/ directory,  when I remove that kafka-client jar file, kop works fine. There must be some class loading conflict problem there! Do you know what I can do to solve this ?

**Comment by BewareMyPower** [comment]
Currently KoP depends on kafka-clients-2.0.0.jar for some common classes and KoP is loaded by broker dynamically, including uncompressing the NAR file and loading the classes.

IMO, It's better not to add other JARs to `lib` directory. This incompatibility issue is hard to test in CI.

**Comment by lujiwen** [comment]
@BewareMyPower OK, thanks a lot, maybe my problem get solved, let me close this issue.
