### ISSUE TITLE
[BUG] Fail to reconnect after bundle unload

### ISSUE THREAD

**Issue by wangjialing218** [streamnative/kop#1111]
**To Reproduce**
Broker version: 2.9.2
KoP version:2.9.2.4

Use benchmark to do performance test.
Kafka producer received NOT_LEADER_OR_FOLLOWER when bundle unload happed and failed to reconnect.

I used multi-listener in k8s, I'm not sure if this is related with multi-listener.

[benchmark.log](https://github.com/streamnative/kop/files/8131479/benchmark.log)
[pulsar.log](https://github.com/streamnative/kop/files/8131480/pulsar.log)
[kop.log](https://github.com/streamnative/kop/files/8131481/kop.log)

**Comment by eolivelli** [comment]
I am seeing the same problem, with OMB.
this is something in my backlog.

it is not related to multi listener in my case

**Comment by wangjialing218** [comment]
I tried  benchmark performance test with workloads `max-rate-1-topic-1-partition-1p-1c-1kb.yaml` and `max-rate-1-topic-20-partitions-20p-20c-1kb.yaml`, and clients could reconnect after bundle unload.
The issue happens when using `max-rate-1-topic-80-partitions-80p-80c-1kb.yaml`.

**Comment by eolivelli** [comment]
I believe that the problem is not about KOP but we have bugs in Pulsar.

In my tests I see that often the problem is about a bundle that is unloaded but it is never recovered.
Some ManagedLedger may stay in "fenced" status forever (without manual intervention, even with `topicFencingTimeoutSeconds=5`).
Sometimes the problem is about a Broker that dies for OutOfMemory error while unloading a bundle.

cc @dave2wave

**Comment by eolivelli** [comment]
In order to trigger the problem you have to have more than one broker and have many topics/partitions, this way you trigger the load balancer.

Probably manual unloading is too "lucky"

**Comment by wangjialing218** [comment]
This issue happened with more than 3 brokers.
TopicA was owned by broker2 and unloaded to broker3, when client send METADATA to broker1 after unload happen, broker1 still return broker2 for TopicA because cache does not clear.
In current implementation broker1 did not received the bundle unload or onload event because the bundle is not its owned bundle.
