### ISSUE TITLE
[BUG] Retention Policy is resetted when restarting Pulsar-Broker with KoP

### ISSUE THREAD

**Issue by daniwb** [streamnative/kop#1143]
Describe the bug
When Pulsar-Broker is restarted in a Cluster, the Retention Policy will be resetted for public/default (or possibly the Namespace where Kafka on Pulsar will use)

To Reproduce

    Set Retention Policy:
    bin/pulsar-admin namespaces set-retention public/default --size 11G --time 1h

    Show Retention Policy:
    bin/pulsar-admin namespaces policies public/default
    ...
    "retention_policies" : {
    "retentionTimeInMinutes" : 60,
    "retentionSizeInMB" : 11264
    },
    ...

    Restart Pulsar Broker
    bin/pulsar-daemon stop broker
    bin/pulsar-daemon start broker

    Check Policies again
    bin/pulsar-admin namespaces policies public/default
    ...
    "retention_policies" : {
    "retentionTimeInMinutes" : 4320,
    "retentionSizeInMB" : -1
    },
    ...
    Expected behavior
    The retention policy should not be changed at all.

"retention_policies" : {
"retentionTimeInMinutes" : 60,
"retentionSizeInMB" : 11264
},

Screenshots

Desktop (please complete the following information):
CentOS 7
Pulsar 2.9.1

Additional context

**Comment by wenbingshen** [comment]
It looks related to this PR: #433.  I'm interested in fixing this, if there's no other reason I'd like to assign to myself first. :) @BewareMyPower @Demogorgon314
