### ISSUE TITLE
[BUG] Problems with brokerDeduplicationEnabled=true

### ISSUE THREAD

**Issue by eolivelli** [streamnative/kop#1225]
**Describe the bug**

If I start KOP on Pulsar standalone (2.8.3, with brokerDeduplicationEnabled=true) and I use kafka-console-producer.sh
kafka_2.13-3.0.0/bin/kafka-console-producer.sh  --bootstrap-server localhost:9092 --topic test

If I send messages too quickly (even with the keyboard), I see this error:

> 
> [2022-04-06 16:10:29,153] ERROR Error when sending message to topic test with key: null, value: 5 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
> org.apache.kafka.common.errors.OutOfOrderSequenceException: The broker received an out of order sequence number.
> [2022-04-06 16:10:29,156] ERROR Error when sending message to topic test with key: null, value: 5 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
> org.apache.kafka.common.errors.OutOfOrderSequenceException: The broker received an out of order sequence number.
> [2022-04-06 16:10:29,156] ERROR Error when sending message to topic test with key: null, value: 4 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
> org.apache.kafka.common.errors.OutOfOrderSequenceException: The broker received an out of order sequence number.
> [2022-04-06 16:10:29,156] ERROR Error when sending message to topic test with key: null, value: 4 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
> org.apache.kafka.common.errors.OutOfOrderSequenceException: The broker received an out of order sequence number.
> 

This is the error on the Broker

> 2022-04-06T16:10:27,555+0200 [BookKeeperClientWorker-OrderedExecutor-0-0] INFO  org.apache.pulsar.broker.service.persistent.MessageDeduplication - [persistent://public/default/test-partition-0] Enabled deduplication
> 2022-04-06T16:10:29,144+0200 [pulsar-ph-kafka-86-2] ERROR io.streamnative.pulsar.handlers.kop.storage.PartitionLog - publishMessages for topic partition: persistent://public/default/test-partition-0 failed when write.
> org.apache.kafka.common.errors.OutOfOrderSequenceException: The broker received an out of order sequence number.
> 2022-04-06T16:10:30,242+0200 [pulsar-ph-kafka-86-2] ERROR io.streamnative.pulsar.handlers.kop.storage.PartitionLog - publishMessages for topic partition: persistent://public/default/test-partition-0 failed when write.

**Expected behavior**
No error

**Comment by Demogorgon314** [comment]
Oh, when we enable the broker deduplication, we must use the idempotent producer to send messages, since we are reusing the pulsar deduplication. See https://github.com/streamnative/kop/issues/1007

I'll add a doc to explain this feature ASAP.

**Comment by Demogorgon314** [comment]
Maybe we can add a config to control the KoP side deduplication.

**Comment by eolivelli** [comment]
current behaviour is not good if you have a namespace in which you want transactional idempotent and non transactional producer.
