### ISSUE TITLE
The purpose of Pulsar 

### ISSUE THREAD

**Issue by HelloTo4x** [streamnative/kop#1325]
Hi, i am reading your project, why don't u use Kafka or RabbitMQ as message queue instead of Pulsar, can you tell me why you choose Pulsar, do you know the pros and cons of Pulsar, if yes, can tell me, thank u so much

**Comment by BewareMyPower** [comment]
KoP is an extension of Pulsar, it makes Pulsar able to support the widely used Kafka API.

It's not a good place here to compare these message systems. You can simply search keywords like "Pulsar vs Kafka" on Google. But I think it's better to read the documents from the official website and judge by yourself.

**Comment by HelloTo4x** [comment]
"support the widely used Kafka API." can u tell me about this

**Comment by BewareMyPower** [comment]
i.e. there are a lot of existing applications that use Kafka API, including:
- Use the Kafka clients directly, including the official Kafka Java client, the librdkafka C client, etc.
- Use Kafka Streams that depends on the Kafka Java client
- Use Kafka Connect or connectors from other software, e.g. the [Apache Kafka Connector](https://nightlies.apache.org/flink/flink-docs-master/docs/connectors/datastream/kafka/) of Flink.
