### ISSUE TITLE
[BUG] poor performance with KOP

### ISSUE THREAD

**Issue by aloyszhang** [streamnative/kop#134]
**Describe the bug**
When test KOP with kafka-producer-perf tool, performance is very poor:
```
$ bin/kafka-producer-perf-test.sh  --topic kop-test --producer.conf config/producer.properties  --throughput -1 --num-records 100000000 --record-size 1024
4036 records sent, 804.8 records/sec (0.79 MB/sec), 2349.0 ms avg latency, 4712.0 max latency.
3735 records sent, 745.2 records/sec (0.73 MB/sec), 7095.8 ms avg latency, 9678.0 max latency.
3600 records sent, 718.0 records/sec (0.70 MB/sec), 12010.2 ms avg latency, 14667.0 max latency.
3645 records sent, 726.7 records/sec (0.71 MB/sec), 17134.9 ms avg latency, 19659.0 max latency.
```
while test with pulsar-perf, performance much more higher 

```
$ bin/pulsar-perf produce -threads 1 -u pulsar://100.76.43.216:6650 -o 10000 -n 4 -b 0 -bm 0 -s 4096 -r 3000000 public/default/kop-test
09:55:10.009 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced:  15882.3  msg/s ---    496.3 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 337.086 ms - med: 236.380 - 95pct: 784.219 - 99pct: 861.987 - 99.9pct: 870.187 - 99.99pct: 870.439 - Max: 870.539
09:55:20.100 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced:  15703.9  msg/s ---    490.7 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1645.813 ms - med: 521.495 - 95pct: 10822.271 - 99pct: 10832.767 - 99.9pct: 10838.975 - 99.99pct: 10839.359 - Max: 10839.359
09:55:30.162 [main] INFO  org.apache.pulsar.testclient.PerformanceProducer - Throughput produced:  15777.3  msg/s ---    493.0 Mbit/s --- failure      0.0 msg/s --- Latency: mean: 1764.075 ms - med: 676.243 - 95pct: 10684.863 - 99pct: 10744.063 - 99.9pct: 10747.455 - 99.99pct: 10749.183 - Max: 10749.247
```

**To Reproduce**
just run kafka-producer-perf  on a KOP supported pulsar cluster
 
**Expected behavior**
 For kafka client, KOP should provide performance same as or close to native pulsar-client

**Comment by jiazhai** [comment]
@PierreZ Seems you have a discussion. And in your env, it could get "1.8 millions of messages per second per partition". Is there a comparing in your env for pulsar and kop?

**Comment by PierreZ** [comment]
@jiazhai I was talking about the bench we did for our prod environment using Pulsar only. I did not deployed KoP yet, so I cannot make a comparaison. 

I must say, I am surprised, but as they say: "If You Don’t Measure It, You Can’t Manage It".

We should dig into these, let me try to run a bench on my side.

**Comment by jiazhai** [comment]
@PierreZ Thanks for the feed back. Thanks @aloyszhang for rise up this issue.
Yes. there should be some place need to parallel. 
May be we can first improve the single thread / single partition performance.  Then do multi-partition performance.

Just sync with @ltamber, For the multi-partition case, there is 1 place could get parallel:
in method "handleProducerRequestInternal",  each request is handled in sequence. If a request contains more than 1 partition, it will wait until all partitions write completed.

**Comment by jiazhai** [comment]
Seems we need to add some metrics to get more internal details, so we can do the analysis.

**Comment by hangc0276** [comment]
I also found the performance problems when using kafka-perf vs. pulsar-perf under one partition topic.
