### ISSUE TITLE
[BUG]Force topic delete is not working when topic has active consumers/producers.

### ISSUE THREAD

**Issue by devprashantksinha** [streamnative/kop#136]
**Describe the bug**
Force topic delete is not working when topic has active consumers/producers.

**To Reproduce**
1. Go inside bastion pod
2. Create a partitioned topic using pulsar-admin client : 
![image](https://user-images.githubusercontent.com/15067043/78861951-bd002900-7a53-11ea-9a68-85e933f7a3ea.png)
3. Create an active consumer in new terminal for the above topic created : 
![image](https://user-images.githubusercontent.com/15067043/78862049-0badc300-7a54-11ea-8f52-aa82e92d4064.png)

4. Force Delete the topic using this command while the consumer is actively running in other terminal: 
![image](https://user-images.githubusercontent.com/15067043/78862142-49aae700-7a54-11ea-9483-64160750c5da.png)

5. Do a topics list to check if the topic is deleted and observe that topic is still listed : 
![image](https://user-images.githubusercontent.com/15067043/78862415-f6856400-7a54-11ea-97a8-405198471543.png)

6. Also try creating topics again and observe below error : 
![image](https://user-images.githubusercontent.com/15067043/78862533-39dfd280-7a55-11ea-9ac9-df5ab138d0d4.png)

**Expected behavior**
Topics should get deleted and topic creation after deletion should work.

This issue is easily reproducible please let me know if more info/logs is required.

**Comment by jiazhai** [comment]
This is more like a Pulsar issue.

**Comment by jiazhai** [comment]
@devprashantksinha The issue may caused by the 3rd step: a consumer is always active at the backend.  Once the topic is force deleted, the consumer will fail to connect, and try to connect again, and will trigger a topic been auto created again.
Would you please try to disconnect the consumer or disable the topic-auto-create ?

**Comment by devprashantksinha** [comment]
@jiazhai : ok . i will try and get back you.

**Comment by devprashantksinha** [comment]
@jiazhai : I tested with latest build available with us. Force delete of the topic having an active consumer when auto-topic creation is disabled is working as expected. 

Let me verify the same with Java Pulsar Client once.
