### ISSUE TITLE
[BUG]KoP README.md has a small bug

### ISSUE THREAD

**Issue by yuanweikang2020** [streamnative/kop#141]
**Describe the bug**
KoP `README.md` has a small bug
![image](https://user-images.githubusercontent.com/63803593/79532449-bef76700-80a7-11ea-812a-c36776537b31.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sijie** [comment]
@yuanweikang2020 are you interested in contributing a bug fix for it?

**Comment by yuanweikang2020** [comment]
Ok，i try it.
