### ISSUE TITLE
[BUG] kafka consumers stop receiving new data from kop

### ISSUE THREAD

**Issue by zbye** [streamnative/kop#1458]
**Describe the bug**

1. we create a partitioned-topic "BD_YD_OrgInsight_STEP", with 10 partitions, using ./pulsar-admin command.
2. we deploy a kafka producer to send data to pulsar continuously and deploy a kafka consumer.
3. Kafka consumer can normally consume part of the data after starting, and then stops receiving new data.  
     At this time, pulsar consumers work well and recevice data normally！

**To Reproduce**
1. Start a consumer  by running a program or using kafka commands .
2. the consumer will receive some data after it is started immediately, and then stops receiving. 
3. This phenomenon can recur stably.

**Expected behavior**
 kafka consumers should receive data normallly.

**Screenshots**

![image](https://user-images.githubusercontent.com/5737494/186054544-1b195561-f5ce-450b-a4c1-62860d91dacf.png)

![image](https://user-images.githubusercontent.com/5737494/186054519-3a0e2c5e-5bf8-499d-84c0-d30d67a05471.png)

 Kafka CLI 工具看到的group 信息如图
![image](https://user-images.githubusercontent.com/5737494/186054488-0668b95f-a64b-4fb5-bd49-7ec51d34543b.png)

**Comment by zbye** [comment]
This is the broker logs (10.100.100.207-209)

[2022-08-22_18_25.zip](https://github.com/streamnative/kop/files/9398728/2022-08-22_18_25.zip)

**Comment by Demogorgon314** [comment]
Look like the broker logs cannot download. Can you check if the link is correct?

**Comment by BewareMyPower** [comment]
In addition to the broken download url, could you describe it in detail?

I see there are 3 consumers from the group describe result, however, you said

> Start a consumer by running a program or using kafka commands .

1. Could you provide your application code or the full Kafka commands? Could you try only one consumer to see if the problem could happen again?
2. How long will this issue happen since your application started? Could you adjust the log level to debug?
3. Could you try reproducing it with only 1 broker available?

**Comment by zbye** [comment]
> Look like the broker logs cannot download. Can you check if the link is correct?

@Demogorgon314 I have uploaded again, thanks.

**Comment by zbye** [comment]
> In addition to the broken download url, could you describe it in detail?
> 
> I see there are 3 consumers from the group describe result, however, you said
> 
> > Start a consumer by running a program or using kafka commands .
> 
> 1. Could you provide your application code or the full Kafka commands? Could you try only one consumer to see if the problem could happen again?
> 2. How long will this issue happen since your application started? Could you adjust the log level to debug?
> 3. Could you try reproducing it with only 1 broker available?

1、We use command ” ./kafka-console-consumer.sh --bootstrap-server  10.100.100.207:9092,10.100.100.208:9092,10..100.100.209:9092 --topic BD_YD_OrgInsight_STEP “ to start a consumer.
the problem  still happens even if only one consumer.
2、It happended  when consumer started immediately, in several second. 
3、we will try when only one broker.

**Comment by zbye** [comment]
[2022-08-23 13_47_01.zip](https://github.com/streamnative/kop/files/9399715/2022-08-23.13_47_01.zip)

@BewareMyPower this is the debug logs after i run command "./kafka-console-consumer.sh --bootstrap-server 10.100.100.207:9092,10.100.100.208:9092,10..100.100.209:9092 --topic BD_YD_OrgInsight_STEP "

**Comment by zbye** [comment]
[root@kxnhhj6f bin]# ./pulsar-admin topics partitioned-stats persistent://public/default/BD_YD_OrgInsight_STEP
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 460.22990341947303,
  "msgThroughputOut" : 131871.9730678956,
  "bytesInCounter" : 801274020,
  "msgInCounter" : 2846790,
  "bytesOutCounter" : 1223963000,
  "msgOutCounter" : 4278205,
  "averageMsgSize" : 0.0,
  "msgChunkPublished" : false,
  "storageSize" : 52206110497,
  "backlogSize" : 46843493,
  "publishRateLimitedTimes" : 0,
  "earliestMsgPublishTimeInBacklogs" : 0,
  "offloadedStorageSize" : 0,
  "lastOffloadLedgerId" : 0,
  "lastOffloadSuccessTimeStamp" : 0,
  "lastOffloadFailureTimeStamp" : 0,
  "publishers" : [ {
    "msgRateIn" : 0.0,
    "msgThroughputIn" : 0.0,
    "averageMsgSize" : 0.0,
    "chunkedMessageRate" : 0.0,
    "producerId" : 0,
    "supportsPartialProducer" : false
  } ],
  "waitingPublishers" : 0,
  "subscriptions" : {
    "dsj_cashflow_service_test_node" : {
      "msgRateOut" : 460.22990341947303,
      "msgThroughputOut" : 131871.9730678956,
      "bytesOutCounter" : 1223963000,
      "msgOutCounter" : 4278205,
      "msgRateRedeliver" : 0.0,
      "chunkedMessageRate" : 0,
      "msgBacklog" : 68544,
      "backlogSize" : 0,
      "earliestMsgPublishTimeInBacklog" : 0,
      "msgBacklogNoDelayed" : 68544,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "msgRateExpired" : 0.0,
      "totalMsgExpired" : 0,
      "lastExpireTimestamp" : 0,
      "lastConsumedFlowTimestamp" : 0,
      "lastConsumedTimestamp" : 0,
      "lastAckedTimestamp" : 0,
      "lastMarkDeleteAdvancedTimestamp" : 0,
      "consumers" : [ {
        "msgRateOut" : 460.22990341947303,
        "msgThroughputOut" : 131871.9730678956,
        "bytesOutCounter" : 648862028,
        "msgOutCounter" : 2266642,
        "msgRateRedeliver" : 0.0,
        "chunkedMessageRate" : 0.0,
        "availablePermits" : -642,
        "unackedMessages" : 0,
        "avgMessagesPerEntry" : 0,
        "blockedConsumerOnUnackedMsgs" : false,
        "lastAckedTimestamp" : 0,
        "lastConsumedTimestamp" : 0
      } ],
      "isDurable" : true,
      "isReplicated" : true,
      "allowOutOfOrderDelivery" : false,
      "consumersAfterMarkDeletePosition" : { },
      "nonContiguousDeletedMessagesRanges" : 30,
      "nonContiguousDeletedMessagesRangesSerializedSize" : 740,
      "subscriptionProperties" : { },
      "durable" : true,
      "replicated" : true
    }
  },
  "replication" : { },
  "nonContiguousDeletedMessagesRanges" : 30,
  "nonContiguousDeletedMessagesRangesSerializedSize" : 740,
  "compaction" : {
    "lastCompactionRemovedEventCount" : 0,
    "lastCompactionSucceedTimestamp" : 0,
    "lastCompactionFailedTimestamp" : 0,
    "lastCompactionDurationTimeInMills" : 0
  },
  "metadata" : {
    "partitions" : 10
  },
  "partitions" : { }
}
[root@kxnhhj6f bin]# ./pulsar-admin topics partitioned-stats persistent://public/default/BD_YD_OrgInsight_STEP
{
  "msgRateIn" : 0.0,
  "msgThroughputIn" : 0.0,
  "msgRateOut" : 460.22990341947303,
  "msgThroughputOut" : 131871.9730678956,
  "bytesInCounter" : 801274020,
  "msgInCounter" : 2846790,
  "bytesOutCounter" : 1223963000,
  "msgOutCounter" : 4278205,
  "averageMsgSize" : 0.0,
  "msgChunkPublished" : false,
  "storageSize" : 52206110497,
  "backlogSize" : 46843493,
  "publishRateLimitedTimes" : 0,
  "earliestMsgPublishTimeInBacklogs" : 0,
  "offloadedStorageSize" : 0,
  "lastOffloadLedgerId" : 0,
  "lastOffloadSuccessTimeStamp" : 0,
  "lastOffloadFailureTimeStamp" : 0,
  "publishers" : [ {
    "msgRateIn" : 0.0,
    "msgThroughputIn" : 0.0,
    "averageMsgSize" : 0.0,
    "chunkedMessageRate" : 0.0,
    "producerId" : 0,
    "supportsPartialProducer" : false
  } ],
  "waitingPublishers" : 0,
  "subscriptions" : {
    "dsj_cashflow_service_test_node" : {
      "msgRateOut" : 460.22990341947303,
      "msgThroughputOut" : 131871.9730678956,
      "bytesOutCounter" : 1223963000,
      "msgOutCounter" : 4278205,
      "msgRateRedeliver" : 0.0,
      "chunkedMessageRate" : 0,
      "msgBacklog" : 68544,
      "backlogSize" : 0,
      "earliestMsgPublishTimeInBacklog" : 0,
      "msgBacklogNoDelayed" : 68544,
      "blockedSubscriptionOnUnackedMsgs" : false,
      "msgDelayed" : 0,
      "unackedMessages" : 0,
      "msgRateExpired" : 0.0,
      "totalMsgExpired" : 0,
      "lastExpireTimestamp" : 0,
      "lastConsumedFlowTimestamp" : 0,
      "lastConsumedTimestamp" : 0,
      "lastAckedTimestamp" : 0,
      "lastMarkDeleteAdvancedTimestamp" : 0,
      "consumers" : [ {
        "msgRateOut" : 460.22990341947303,
        "msgThroughputOut" : 131871.9730678956,
        "bytesOutCounter" : 648862028,
        "msgOutCounter" : 2266642,
        "msgRateRedeliver" : 0.0,
        "chunkedMessageRate" : 0.0,
        "availablePermits" : -642,
        "unackedMessages" : 0,
        "avgMessagesPerEntry" : 0,
        "blockedConsumerOnUnackedMsgs" : false,
        "lastAckedTimestamp" : 0,
        "lastConsumedTimestamp" : 0
      } ],
      "isDurable" : true,
      "isReplicated" : true,
      "allowOutOfOrderDelivery" : false,
      "consumersAfterMarkDeletePosition" : { },
      "nonContiguousDeletedMessagesRanges" : 30,
      "nonContiguousDeletedMessagesRangesSerializedSize" : 740,
      "subscriptionProperties" : { },
      "durable" : true,
      "replicated" : true
    }
  },
  "replication" : { },
  "nonContiguousDeletedMessagesRanges" : 30,
  "nonContiguousDeletedMessagesRangesSerializedSize" : 740,
  "compaction" : {
    "lastCompactionRemovedEventCount" : 0,
    "lastCompactionSucceedTimestamp" : 0,
    "lastCompactionFailedTimestamp" : 0,
    "lastCompactionDurationTimeInMills" : 0
  },
  "metadata" : {
    "partitions" : 10
  },
  "partitions" : { }
}

**Comment by BewareMyPower** [comment]
> [2022-08-23 13_47_01.zip](https://github.com/streamnative/kop/files/9399715/2022-08-23.13_47_01.zip)
> 
> @BewareMyPower this is the debug logs after i run command "./kafka-console-consumer.sh --bootstrap-server 10.100.100.207:9092,10.100.100.208:9092,10..100.100.209:9092 --topic BD_YD_OrgInsight_STEP "

The debug log level was not enabled. See the instruction [here](https://github.com/streamnative/kop/blob/master/docs/configuration.md#logger), if the logs are written into the file, e.g. start the broker in background (`pulsar-daemon start broker`), you need to change the `ref` from `Console` to `RollingFile`.

BTW, I found the following log appeared frequently in broker-log-2.txt:

> WARN  org.apache.pulsar.broker.namespace.NamespaceService - Broker http://10.100.100.209:8080 (10.100.100.209:8080) couldn't be found in available brokers 10.100.100.207:8080,10.100.100.208:8080
> WARN  org.apache.pulsar.broker.namespace.NamespaceService - The current leader broker LeaderBroker(serviceUrl=http://10.100.100.209:8080) isn't active. Handling load manager decisions in a decentralized w       ay. NamespaceBundle[gmtp/sse_SHL2/0xc0000000_0xffffffff]

The HTTP endpoint of broker in 10.100.100.209 is available. There might be something wrong with the load manager, could you help take a look? @Demogorgon314

**Comment by zbye** [comment]
[2022-08-24 kop-log.zip](https://github.com/streamnative/kop/files/9411797/2022-08-24.kop-log.zip)

This the broker's log (kop related logs are printed in pulsar-broker-kop-xxx.txt)

**Comment by zbye** [comment]
This broker configs's example : 
[broker-01.conf.txt](https://github.com/streamnative/kop/files/9411881/broker-01.conf.txt)

**Comment by zbye** [comment]
[broker-configs-08-24.zip](https://github.com/streamnative/kop/files/9412047/broker-configs-08-24.zip)

config files for all brokers.
