### ISSUE TITLE
[BUG] Cannot submit offset correctly

### ISSUE THREAD

**Issue by lwclover** [streamnative/kop#1500]
**Describe the bug**
<img width="456" alt="81ad161cc951006f0395748d9fa2270" src="https://user-images.githubusercontent.com/4252409/190936906-9501ed87-395b-450f-a65f-85c14a47acbe.png">

`                    long baseOffset = MessageMetadataUtils.getMockOffset(
                        lastMessageId.getLedgerId(),
                        lastMessageId.getEntryId()
                    );`
The baseOffset is not monotonically increasing, consumer cannot submit offset correctly.
The offset can be detected incorrectly through Kafka Exporter.

**To Reproduce**
Normal consumption messages can reproduce the bug.

**Comment by sikangliu** [comment]
@lwclover Do you have security authentication enabled when you use kop? If this is enabled, what should username be configured as?
