### ISSUE TITLE
How kafka client  1.0+ work with kop

### ISSUE THREAD

**Issue by hangc0276** [streamnative/kop#151]
### Motivation
In my production environment, kafka broker version is 1.1.1 and most kafka clients are various, such as rdkafka 1.0+, kafka-python, kafka-client 1.0+, flink-connector-kafka_2.11, pykafka, and the client version maybe also various.

I need to immigrate the applications which worked with kafka to pulsar using kop, but i am afraid there are some unknown features that the current kop not support, cloud you give me some ideas? @sijie @jiazhai

**Comment by jiazhai** [comment]
@hangc0276 Current [integration tests](https://github.com/streamnative/kop/tree/master/integrations) covers some comment features. We could add a test for `kafka-client 1.0+`, `rdkafka 1.0+` in it to identify it out the not supported features.
