### ISSUE TITLE
[FEATURE] Pulsar Kop should support Kafka 2.1+ version 

### ISSUE THREAD

**Issue by fenghao007** [streamnative/kop#153]
Currently Kop Only Support Kafka 2.0.  The latest Kafka version has come to 2.5. 
The most important is since Kafka 2.1,  there are some changes  for the schema used to store consumer offsets  which makes current Kop cannot support Kafka 2.1 and all subsequent incremental version .   [Kafka schema changed related docs . ](https://kafka.apache.org/21/documentation.html#upgrade)
I hava perfomed some  kop tests with @codelipenghui  , Using  Kafka 2.3 and Kafka 2.0 clients .   Kafka 2.0 client work well .
While  Kafka 2.3 clients , it will always give a following error which Verified my conjecture. 

`06:48:16.138 [pulsar-io-22-14] ERROR io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - Caught error in handler, closing channel
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 104857600: 369295621 - discarded
        at io.netty.handler.codec.LengthFieldBasedFrameDecoder.fail(LengthFieldBasedFrameDecoder.java:513) ~[io.netty-netty-codec-4.1.43.Final.jar:4.1.43.Final]
`

Now we're going to quickly  immigrate our production to pulsar with kop . It can really reduce the cost of immigration esp. it  can be  transparent to business.  Kop not support Kafka 2.3 has blocked us . 
What's more , Kop need this support  Kafka 2.1+  , it may be more popular and used  .  @jiazhai @sijie

**Comment by sijie** [comment]
@fenghao007 noted. we will prioritize to add the support for Kafka 2.1+ clients.

**Comment by thinker0** [comment]
+1

**Comment by jsyvanen** [comment]
+1

**Comment by jiazhai** [comment]
This is already done, will close this issue
