### ISSUE TITLE
[BUG] End to End Latency is more a function of message size than throughput

### ISSUE THREAD

**Issue by dave2wave** [streamnative/kop#1553]
**Describe the bug**
I do regular OpenMessaging Benchmarks using DataStax's forks of KoP and OMB. One of the tests is 400,000 messages per second of 1K messages. I did an experiment by adding a stepwise increase of production to OMB to see if latency was a function of throughput. The stepwise version started at 20000 messages per second and increased by 20000 every 30 seconds. The results for both runs was remarkably similar.

<img width="1019" alt="Screen Shot 2022-10-31 at 3 38 19 PM" src="https://user-images.githubusercontent.com/29803617/199123259-87ba0d51-33ad-4b81-bf8c-7361c23e7959.png">
<img width="1005" alt="Screen Shot 2022-10-31 at 3 38 44 PM" src="https://user-images.githubusercontent.com/29803617/199123263-9da84e77-a63a-43c7-86a4-4bd1ec39bc93.png">

I took flight recordings of these runs on the brokers and noticed two issues.

1. Over 20% of time was spent in CRC32C.update. These are byte by byte updates, but the optimized CRC32C is not used. I've added information to #971 
2. Also time is spent in java.io.DataStreamOutput.writeByte. I would like to focus on why that might be so.

<img width="873" alt="Screen Shot 2022-10-31 at 3 46 50 PM" src="https://user-images.githubusercontent.com/29803617/199124159-90c36338-faca-40a5-8076-fdfef4e0a733.png">

If you look at the Kafka routine. Utils.writeTo: https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/common/utils/Utils.java#L1193-L1209

You see that if the ByteBuffer is backed by an Array it will choose to writeTo in a more efficient way than byte by byte.

As near as I can tell the kind of ByteBuffer created is determined here:

**To Reproduce**
4. Click on '....'
5. Scroll down to '....'
6. See error

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dave2wave** [comment]
I am seeing some changes in the code on the hot path here. Closing for now.

**Comment by Demogorgon314** [comment]
@dave2wave Can you try to apply this change? This PR improved the latency issue. https://github.com/streamnative/kop/pull/1423

**Comment by dave2wave** [comment]
@Demogorgon314 PR #1469 also changed code on the my observed stacktrace.
