### ISSUE TITLE
[BUG] SASL config does not take effect

### ISSUE THREAD

**Issue by Gleiphir2769** [streamnative/kop#1569]
**Describe the bug**
Hi, I want to enable PLAIN authentication. But it does not take effect.

THis is my KOP config.

```
subscriptionKeySharedEnable=true
messagingProtocols=kafka
protocolHandlerDirectory=/pulsar/protocols
kafkaListeners=PLAINTEXT://x.x.x.x:9092
brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor
entryFormat=kafka
kafkaTenant=kafka_tenant
kafkaNamespace=kafka
kafkaMetadataTenant=kafka_meta
saslAllowedMechanisms=PLAIN
```

This is my client log:
```
[2022-11-16 04:24:49,490] ERROR [Producer clientId=console-producer] Connection to node -1 failed authentication due to: Unexpected handshake request with client mechanism PLAIN, enabled mechanisms are [] (org.apache.kafka.clients.NetworkClient)
```

It seems broker does not enabled sasl. Do I miss something?

ver: 2.10.1

**Comment by Demogorgon314** [comment]
Can you share the client-side config?

**Comment by Demogorgon314** [comment]
Do you set the `authenticationEnabled=true`? See: https://github.com/streamnative/kop/blob/master/docs/security.md#plain

**Comment by Gleiphir2769** [comment]
> Do you set the `authenticationEnabled=true`? See: https://github.com/streamnative/kop/blob/master/docs/security.md#plain

@Demogorgon314 Thanks! Finally we find the problem is caused by our starting shell. And indeed `authenticationEnabled=true` is not configured.
