### ISSUE TITLE
[BUG] log-end-offset becomes a negative number

### ISSUE THREAD

**Issue by lwclover** [streamnative/kop#1634]
**Describe the bug**
<img width="297" alt="4ec69d4060c625ed876d0ce9961d469" src="https://user-images.githubusercontent.com/4252409/208341578-652c04c3-1378-487d-ba6b-95038ec05e07.png">

After running normally on production for a long time, it turns negative.
No broker outages occured,

**Comment by lwclover** [comment]
Master branch has repaired it

**Comment by Demogorgon314** [comment]
This bug was introduced by #1060 and fixed by #1588.
