### ISSUE TITLE
[BUG] Plugin can overwrite the cluster metadata

### ISSUE THREAD

**Issue by wmccarley** [streamnative/kop#167]
**Describe the bug**
This plugin has [code](https://github.com/streamnative/kop/blob/master/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java#L349) that overwrites the existing cluster metadata in the global zookeeper for the Pulsar cluster:

```java
String cluster = kafkaConfig.getClusterName();
...
ClusterData clusterData = new ClusterData(service.pulsar().getWebServiceAddress(),
  null /* serviceUrlTls */,
  service.pulsar().getBrokerServiceUrl(),
  null /* brokerServiceUrlTls */);
 if (!pulsarAdmin.clusters().getClusters().contains(cluster)) {
  pulsarAdmin.clusters().createCluster(cluster, clusterData);
} else {
  pulsarAdmin.clusters().updateCluster(cluster, clusterData);
}
```

In my opinion the `createKafkaMetadataNamespaceIfNeeded` method should throw a `PulsarServerException` if the cluster does not exist and _**should not**_ overwrite the clusterData if it does exist.

I can submit a PR for this, it is a trivial change, but I just want to understand if I am missing something here? Modifying cluster metadata is a significant operation that can have immediate effects on the entire cluster, I can't envision a circumstance where the plugin should attempt to modify this data at all.

**Comment by jiazhai** [comment]
Thanks @wmccarley for reporting this issue. you are right, we should not overwrite the existing cluster data.

**Comment by wmccarley** [comment]
@jiazhai I have created #168 which addresses this issue. As noted in the comments, this fails KafkaIntegrationTest in node-rdkafka but I cannot figure out why.
