### ISSUE TITLE
[BUG]The request.timeout.ms setting is too large to cause broker full gc or oom

### ISSUE THREAD

**Issue by keyboardbobo** [streamnative/kop#1739]
**Describe the bug**
The request.timeout.ms setting is too large to cause broker full gc or oom. 

The reason is that after the batch data is sent, producePurgatory will not clean up the delayed task DelayedProduceAndFetch in time, it needs to wait until the delayed task expires to trigger the clearing

**To Reproduce**
1. request.timeout.ms set relatively large, or even Integer.MAX_VALUE
2. Start the stress test client
3. OutOfMemoryError will appear after a while

**Expected behavior**
The broker runs stably

**Comment by BewareMyPower** [comment]
I think you should better setting the publish rate instead of depending on the request.timeout.ms, which was added only to avoid some bugs that make KoP hang.

**Comment by keyboardbobo** [comment]
> I think you should better setting the publish rate instead of depending on the request.timeout.ms, which was added only to avoid some bugs that make KoP hang.

The scene of this problem is to use MirrorMaker2 for data migration. It sets the `request.timeout.ms = Integer.max_value`, so that the problem is caused. If the client is set up by mistake, it is easy to cause cluster stability. Realization, Kafka will also cancel the delay mission after meeting the high water level conditions

**Comment by BewareMyPower** [comment]
**You should set the publish rate to avoid OOM.** It's the same for Pulsar.

**Comment by keyboardbobo** [comment]
> **You should set the publish rate to avoid OOM.** It's the same for Pulsar.

We have a small sending rate, but this problem has nothing to do with the rate. It is a memory leak

**Comment by keyboardbobo** [comment]
> **You should set the publish rate to avoid OOM.** It's the same for Pulsar.

![23C65840-9AFE-456D-9545-220B336471C3](https://user-images.githubusercontent.com/9923278/221812789-adf8bebb-5296-4a3f-946e-bdf797462d56.png)
We have a small sending rate, but this problem has nothing to do with the rate. It is a memory leak

**Comment by BewareMyPower** [comment]
Got it. So it can be reproduced by configuring `request.timeout.ms` with `Integer.MAX_VALUE`?

**Comment by keyboardbobo** [comment]
> Got it. So it can be reproduced by configuring `request.timeout.ms` with `Integer.MAX_VALUE`?

`request.Timeout.ms` configuration value determines the time of the time of the delay task. Set to `Integer.MAX_VALUE` represents the backlog of the memory forever, and it will not be removed.

**Comment by BewareMyPower** [comment]
Ideally, this delayed task should be removed once the callback is triggered even if it does not time out. I will write a test to verify it.

**Comment by keyboardbobo** [comment]
> Ideally, this delayed task should be removed once the callback is triggered even if it does not time out. I will write a test to verify it.

Yes, it should be cleared after all production tasks are completed. we have fixed it...

**Comment by BewareMyPower** [comment]
> we have fixed it...

Could you open a PR if you have fixed it?

**Comment by keyboardbobo** [comment]
> > we have fixed it...
> 
> Could you open a PR if you have fixed it?

Ok, I'll submit the PR late
