### ISSUE TITLE
[BUG] Get a NONE error when getting broker's config

### ISSUE THREAD

**Issue by hi-rustin** [streamnative/kop#1836]
**Describe the bug**
Get a NONE error when getting broker's config.
When I use v2.11.1.0, I will get a NONE error from the response. But if I use v2.9.4.6, then it works.

**To Reproduce**
1. Start a kop with this docker-compose file: https://github.com/streamnative/kop/blob/master/docs/kop.md#run-kop-in-pulsar-with-component-for-each-system-using-docker-compose
2. Use the version 2.11.1.0
3. Follow these steps to create a changefeed in TiCDC: https://github.com/pingcap/tiflow/pull/8893#issuecomment-1537081116
4. Check the error
```log
➜  bin git:(master) ./cdc cli changefeed create --sink-uri="kafka://10.xxx.27:9092/testdsada?max-message-bytes=1048576&protocol=canal-json&kafka-version=2.9.0&replication-factor=1" --config=./changefeed.toml
Error: [CDC:ErrKafkaNewProducer]new kafka producer: [CDC:ErrReachMaxTry]reach maximum try: 3, error: NONE: NONE

[2023/05/06 16:49:31.958 +08:00] [WARN] [admin.go:100] ["query kafka cluster meta failed, retry it"] [namespace=] [changefeed=] [error=NONE]
[2023/05/06 16:49:31.960 +08:00] [DEBUG] [sarama.go:128] ["Closing Client"] [component=sarama]
```
**Expected behavior**
Same as v2.9.4.6, it creates the changefeed success.(Get the configs success).

**Additional context**
We use [Sarama](https://github.com/Shopify/sarama) as our Kafka go client.

**Comment by BewareMyPower** [comment]
Could you try reproducing it with a Sarama based application instead of a ticdc sink?
