### ISSUE TITLE
[BUG] When the Kafka Producer sets acks=0 to send messages to KoP, an error will be throw 

### ISSUE THREAD

**Issue by ric0820** [streamnative/kop#1875]
**Describe the bug**
When the Kafka Producer sets acks=0 to send messages to KoP, an error will be thrown. The exception message is as follows:
```
java.lang.IllegalStateException: There are no in-flight requests for node
```
![image](https://github.com/streamnative/kop/assets/112458501/dd5c83a8-a3c1-4ff1-afe1-944e657e6751)

- kop version 2.10.3 （This can also be reproduced when using kop 2.9.x）
- kafka client version 2.5.0

The above phenomenon can also be consistently reproduced when sending messages using kafka bin/./kafka-producer-perf-test.sh.
```
./kafka-producer-perf-test.sh --topic perf-test-rep2-p30 \
--num-records 10 \
--record-size 1024 \
--throughput 1 \
--producer-props \
acks=0 \
bootstrap.servers={}
```

- kafka version: kafka_2.11-2.4.1/bin

**To Reproduce**
1. download kafka_2.11-2.4.1 and extract  `wget https://archive.apache.org/dist/kafka/2.4.1/kafka_2.11-2.4.1.tgz`
2. enter the bin directory, and execute the corresponding script.
```
./kafka-producer-perf-test.sh --topic perf-test-rep2-p30 \
--num-records 10 \
--record-size 1024 \
--throughput 1 \
--producer-props \
acks=0 \
bootstrap.servers={}
```

**Expected behavior**
no error thrown

**Comment by SunDapeng1** [comment]
On the kafka client, when acks=0, the client creates an empty respone for the producer request

On the kafka server, if acks=0 is detected in the produce request, the server will no longer respond to the request

However, in kop, the server does not distinguish acks and  respond it , which overwrites the empty respone created by the client and carries out subsequent processing logic. 

So you get the error "There are no in-flight requests for node"

**Comment by BewareMyPower** [comment]
I see your PR. Could you add a test to protect it?
