### ISSUE TITLE
[BUG] Memory leak of the map in ThreadLocalAccessor

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#1956]
**Describe the bug**

There are many entries in `ThreadLocalAccessor#map`, whose size is 2885059.

https://github.com/streamnative/kop/blob/ae5d500b293795e9f3b7680cfb07d05366409860/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/ThreadLocalAccessor.java#L21-L23

**To Reproduce**

It happened in SN's test environment with KoP 2.11.1.3. The process ran with `-XX:ActiveProcessorCount=4` so it does not hit the issue here: https://github.com/streamnative/kop/issues/1278. From the thread dump, we can see only one thread (`metrics-90-1`) for it.

**Expected behavior**

The map should not take so much memory.

**Screenshots**

<img width="1688" alt="image" src="https://github.com/streamnative/kop/assets/18204803/282f4176-121c-4b05-8fd9-b9f7838cf0eb">

**Additional context**

**Comment by BewareMyPower** [comment]
<img width="1593" alt="image" src="https://github.com/streamnative/kop/assets/18204803/75300e73-6071-4896-ab97-7f568529abd0">

It's the value of the key `kop_server_PREPARE_METADATA` in `PrometheusMetricsProvider.opStats`.

**Comment by zhouxy0809** [comment]
This problem also reproduce in my prod-env. I’m confused that the metric of `kop_server_PREPARE_METADATA` is one of many `PrometheusMetricsProvider.opStats`，just only this metric could lead memory leak in `ThreadLocalAccessor` from heap dump.

**Comment by lifepuzzlefun** [comment]
@BewareMyPower https://github.com/streamnative/kop/blob/844adb426dbf5ba78ecfc934a90db7c20300d021/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/stats/DataSketchesOpStatsLogger.java#L104-L115 if we clean up all the values in ThreadLocal map when rotate seems can avoid memory leak, but i didn't check if this way will cause the performance issue. If we think this is acceptable i can help to sumit a pr to fix in this way.

**Comment by BewareMyPower** [comment]
Reopen this issue since the metrics expiration cannot fix the frequent GC in short time.
