### ISSUE TITLE
[FEATURE] request new kop version release

### ISSUE THREAD

**Issue by NiuBlibing** [streamnative/kop#2020]
Hello, pulsar 3.0.1 and 3.1.0 had published, is there some plan for Adapting them?

**Comment by BewareMyPower** [comment]
StreamNative switched the KoP release to the private versions recently. For the open sourced version, I might add a workflow for releasing them soon.

**Comment by NiuBlibing** [comment]
Is it means that the kop will not maintained for the open source version?

**Comment by BewareMyPower** [comment]
The open source version will still be maintained but recently we don't have much time on it.

**Comment by BewareMyPower** [comment]
If you're going to use the latest releases, you can pull the `streamnative/sn-pulsar` image. For example,

```bash
docker pull streamnative/sn-pulsar:3.1.0.5
docker pull streamnative/sn-pulsar:3.0.1.5
```

If you don't want to use the image directly, you can copy the NAR file from `/pulsar/protocols` directory from the container.

**Comment by NiuBlibing** [comment]
I'm using apache' binary, is it compatible with sn-pulsar's nar file?

**Comment by BewareMyPower** [comment]
Yes, it follows the rule here: https://github.com/streamnative/kop/blob/master/docs/upgrade.md#upgrade-pulsar

i.e. KoP 3.1.0.5 is compatible with Apache Pulsar 3.1.0

**Comment by BewareMyPower** [comment]
Close it by https://github.com/streamnative/kop/releases/tag/v3.1.1.1
