### ISSUE TITLE
[BUG] caught IllegalArgumentException if batch size > 4096

### ISSUE THREAD

**Issue by dockerzhang** [streamnative/kop#218]
**Describe the bug**
caught IllegalArgumentException if batch size > 4096

**To Reproduce**
1. create a new topic --- t2
2. producer message with `batch size 5000`
`./rdkafka_performance -P -t t2 -b 127.0.0.1:9092 -s 128 -a 1 -X batch.num.messages=5000 -c 1000000`
3. consume
`./rdkafka_performance -C -t t2 -b 127.0.0.1:9092 -G g2`

**Expected behavior**
consume correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/18047329/97979367-fb9f6b80-1e09-11eb-9e63-17a400ee7a02.png)

**Comment by dockerzhang** [comment]
it's related to https://github.com/streamnative/kop/issues/175

**Comment by BewareMyPower** [comment]
Since continuous offset is already supported, this issue will no longer happen.
