### ISSUE TITLE
[BUG] the topic can not remove after the producer and consumer finished

### ISSUE THREAD

**Issue by dockerzhang** [streamnative/kop#229]
**Describe the bug**
the topic can not remove after the producer and consumer finished.

**To Reproduce**
1, create a partitioned topic
`pulsar-admin persistent create-partitioned-topic t-kop/ns-kop/lookup2 --partitions 30`
2, produce `100` message using the created topic
3, consume all produced messages.
4, delete the used topic `lookup2` with pulsar command
`./bin/pulsar-admin topics delete-partitioned-topic  t-kop/ns-kop/lookup2`
5, See error:
`Failed to perform http delete request: javax.ws.rs.ClientErrorException: HTTP 412 Precondition Failed
Topic has active producers/subscriptions`

**Expected behavior**
the topic can remove after the producer and consumer finished.

**Screenshots**
![image](https://user-images.githubusercontent.com/18047329/98894624-22336580-24e0-11eb-95fd-32fe5d213768.png)

**Comment by BewareMyPower** [comment]
Yeah, it's an existed issue for a long time because the `OffsetAcker` holds consumers for acknowledgement. I think there's a better way to do it.

**Comment by jiazhai** [comment]
added comments in the PR
