### ISSUE TITLE
[FE] performance improvement discussion

### ISSUE THREAD

**Issue by yuanboliu** [streamnative/kop#237]
Discussion about this piece of code

```
Queue<Pair<CompletableFuture<ByteBuf>, CompletableFuture<PartitionResponse>>> topicQueue =
                transQueue.get(topic);
        // loop from first responseFuture.
        while (topicQueue != null && topicQueue.peek() != null
                && topicQueue.peek().getLeft().isDone() && isActive.get()) {
            CompletableFuture<Long> offsetFuture = new CompletableFuture<>();
```

I've found the code above has big performance impact on publishing message. Since we make a queue for partition writing, the next partition will never get messages until the last partition has finished. This may lead to performance degression when the system gets a lot of requests. I'd propose to remove the queue for patition-level writing since we have a queue for request-level. But I'm not sure whether this change would bring side effection. I open this thread and hope get feedback from community, thanks for any comment in advance.

**Comment by jiazhai** [comment]
@yuanboliu Agree on the performance penalty, we could make it parallel.

**Comment by yuanboliu** [comment]
ok, I'll create a pr for it.
