### ISSUE TITLE
[BUG] Flume 1.9.0 KafkaSource cannot consume

### ISSUE THREAD

**Issue by shaolilanse** [streamnative/kop#261]
pulsar KOP通过kafka java客户端无法正常消费
kafka java客户端使用Flume的kafkaSource进行消费，通过kafkaSink可以正常生产数据

**To Reproduce**
1. 准备环境：
kop version：0.3.0；pulsar version： 2.6.1；kafka client version：2.0.5
kafka java客户端使用Flume的kafkaSource进行消费，
flume.conf配置如下
`a1.sources =  r1
a1.sinks =  s1
a1.channels = c1
a1.sources.r1.topic = test
a1.sources.r1.type = org.apache.flume.source.kafka.KafkaSource
a1.sources.r1.brokerList = localhost:9092
a1.sources.r1.groupId = cousumer_group_lsl
a1.sources.r1.batchSize = 2
a1.sources.r1.queue_size = 10
a1.sources.r1.batchDurationMillis = 1000
a1.sources.r1.threads = 1
a1.sources.r1.pollTimeOut = 1000
a1.sources.r1.auto.commit.enable = true
a1.sources.r1.kafka.session.timeout.ms = 10000
a1.sources.r1.kafka.max.poll.interval.ms = 300000
a1.sources.r1.kafka.connections.max.idle.ms = -1
a1.sources.r1.channels = c1
a1.channels.c1.type = memory
a1.channels.c1.capacity = 200
a1.channels.c1.transactionCapacity = 100
a1.sinks.s1.type = null
a1.sinks.s1.channel = c1`

2. 向topic[test]中生产消息以供kafka jave客户端消费，
`bin/kafka-console-producer.sh --broker-list localhost:9092  --topic test`
3. kafka java客户端开启debug日志级别，日志信息如下
`[2020-12-11 11:05:08,278] DEBUG (main-kakfa-source-0-test org.apache.kafka.clients.consumer.internals.Fetcher 212) Fetch request to 127.0.0.1:9092 (id: 782843879 rack: null) for partitions [test-0] failed
org.apache.kafka.common.errors.UnsupportedVersionException: The broker is too new to support FETCH version 3`

4. 查看pulsar的broker.log日志
`10:31:11.165 [pulsar-web-42-80] INFO  org.eclipse.jetty.server.RequestLog - 127.0.0.1 - - [11/Dec/2020:10:31:11 +0800] "GET /admin/v2/persistent/public/default/test/partitions HTTP/1.1" 200 16 "-" "Pulsar-Java-v2.6.1" 2
10:31:49.922 [pulsar-load-manager-3-1] INFO  org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl - Only 1 broker available: no load shedding will be performed
10:31:52.426 [pulsar-timer-52-1] INFO  org.apache.pulsar.client.impl.ProducerStatsRecorderImpl - [public/__kafka/__consumer_offsets-partition-0] [pulsar-cluster-1-0-0] Pending messages: 0 --- Publish throughput: 0.20 msg/s --- 0.00 Mbit/s --- Latency: med: 3.000 ms - 95pct: 3.000 ms - 99pct: 3.000 ms - 99.9pct: 3.000 ms - max: 3.000 ms --- Ack received rate: 0.20 ack/s --- Failed messages: 0`

**Expected behavior**
FLume kafkaSource能够正常消费

**Additional context**
使用kafka脚本bin/kafka-console-consumer.sh可以正常消费该topic

**Comment by sijie** [comment]
@BewareMyPower @jiazhai Please help with this issue.

**Comment by BewareMyPower** [comment]
The description is a little confused.

> pulsar KOP通过kafka java客户端无法正常消费

> 使用kafka脚本bin/kafka-console-consumer.sh可以正常消费该topic

Do you mean topics cannot be consumed by **Flume Kafka source** but not **Kafka Java client**? And Kafka Client 2.0.x doesn't have 2.0.5, did you mean 2.5.0.

Also it would be helpful to know your flume version so that I can check the version of Kafka Client and what Flume Kafka source does.

**Comment by BewareMyPower** [comment]
Also, You can add following config code to `conf/log4j.yaml`:

```yaml
      - name: io.streamnative.pulsar.handlers.kop
        level: debug
        additivity: false
        AppenderRef:
          - ref: Console
```

Then KoP's debug logs would be printed to `logs/pulsar-broker-xxx.out`. And make sure `immediateFlush` is true in `conf/log4j.yaml` so that logs can be flushed to files immediately.

**Comment by shaolilanse** [comment]
我这里的Kafka Java client使用的是Flume里的Kafka source组件（http://flume.apache.org/releases/content/1.9.0/FlumeUserGuide.html#http-sink），2.0.5指的是flume服务里引用的kafka-client.jar的版本。当然现在flume官网提供的最新flume版本是引用的以下kafka-client版本

然后我刚尝试自己写个demo引用kafka-clients 2.0.0去测试消费，是可以正常消费的。怀疑是flume里引用的kafka版本问题，但具体原因还不确定










在 2020-12-11 11:58:38，"Yunze Xu" <notifications@github.com> 写道：

The description is a little confused.

pulsar KOP通过kafka java客户端无法正常消费

使用kafka脚本bin/kafka-console-consumer.sh可以正常消费该topic

Do you mean topics cannot be consumed by Flume Kafka source but not Kafka Java client? And Kafka Client 2.0.x doesn't have 2.0.5, did you mean 2.5.0.

Also it would be helpful to know your flume version so that I can check the version of Kafka Client and what Flume Kafka source does.

**Comment by BewareMyPower** [comment]
From my tests, the flume 1.9 works well with Pulsar 2.6.1 + KoP.

I downloaded flume 1.9 from http://www.apache.org/dyn/closer.lua/flume/1.9.0/apache-flume-1.9.0-bin.tar.gz. The Kafka Client's version is 2.0.1. You can find these libs in lib directory:

```bash
$ ls lib | grep kafka-cl
kafka-clients-2.0.1.jar
```

And my config file is a little different

```properties
a1.sources = r1
a1.sinks = s1
a1.channels = c1
a1.sources.r1.topic = my-topic
a1.sources.r1.type = org.apache.flume.source.kafka.KafkaSource
a1.sources.r1.brokerList = localhost:9092
a1.sources.r1.groupId = cousumer_group_lsl
a1.sources.r1.batchSize = 2
a1.sources.r1.queue_size = 10
a1.sources.r1.batchDurationMillis = 1000
a1.sources.r1.threads = 1
a1.sources.r1.pollTimeOut = 1000
a1.sources.r1.auto.commit.enable = true
# 1. the previous brokerList config doesn't work, so I configured kafka.bootstrap.servers here
a1.sources.r1.kafka.bootstrap.servers = localhost:9092
a1.sources.r1.kafka.session.timeout.ms = 10000
a1.sources.r1.kafka.max.poll.interval.ms = 300000
a1.sources.r1.kafka.connections.max.idle.ms = -1
a1.sources.r1.channels = c1
a1.channels.c1.type = memory
a1.channels.c1.capacity = 200
a1.channels.c1.transactionCapacity = 100
# 2. Sink the output to file under logs directory
a1.sinks.s1.type = file_roll
a1.sinks.s1.channel = c1
a1.sinks.s1.sink.directory = logs
```

Then run:

```bash
./bin/flume-ng agent -c ./conf -f ./conf/flume.conf -name a1 -property flume.root.logger=INFO
```

Then I wrote some messages to topic `my-topic` by Kafka Client. Here're the files under logs:

```bash
$ ls logs/160767*
logs/1607677724209-1 logs/1607677724209-2 logs/1607677724209-3 logs/1607677724209-4 logs/1607678152540-1 logs/1607678152540-2 logs/1607678152540-3
$ cat logs/160767*
hello-kop
hello-kop-0
hello-kop-1
hello-kop-2
hello-kop-3
hello-kop-4
hello-kop-5
hello-kop-6
hello-kop-7
hello-kop-8
hello-kop-9
```

**Comment by shaolilanse** [comment]
Now I have changed my flume config,  a1.sinks.s1.type = file_roll, then I can alse see the consumed data from pulsar. 
But I have another problem,  if you config your flume by using kafkaSource and kafkaSink , making consumed data from pulsar(topicA) to another topic(topicB) of pulsar, is that ok? Is there data inside topicB of pulsar ?
eg:
`a1.sources =  r1
a1.sinks =  s1
a1.channels = c1

# [source]
a1.sources.r1.kafka.topics = test101
a1.sources.r1.type = org.apache.flume.source.kafka.KafkaSource
a1.sources.r1.kafka.bootstrap.servers = localhost:9092
a1.sources.r1.kafka.consumer.group.id = cousumer_group_lsl
a1.sources.r1.batchSize = 2
a1.sources.r1.queue_size = 10
a1.sources.r1.batchDurationMillis = 1000
a1.sources.r1.threads = 1
a1.sources.r1.pollTimeOut = 1000
a1.sources.r1.auto.commit.enable = true
a1.sources.r1.kafka.session.timeout.ms = 10000
a1.sources.r1.kafka.max.poll.interval.ms = 300000
a1.sources.r1.kafka.connections.max.idle.ms = -1

# [source channel]
a1.sources.r1.channels = c1

# [memory channel]
a1.channels.c1.type = memory
a1.channels.c1.capacity = 200
a1.channels.c1.transactionCapacity = 100

# [sink]
a1.sinks.s1.type = org.apache.flume.sink.kafka.KafkaSink
a1.sinks.s1.threadpoll_timeout_ms = 6000
a1.sinks.s1.threads = 1
a1.sinks.s1.kafka.bootstrap.servers = localhost:9092
a1.sinks.s1.kafka.key.serializer = org.apache.kafka.common.serialization.StringSerializer
a1.sinks.s1.kafka.topic = test102
a1.sinks.s1.kafka.queue_size = 100
a1.sinks.s1.batchSize = 5
a1.sinks.s1.kafka.producer.batch.size = 500000
a1.sinks.s1.kafka.producer.buffer.memory=536870912
a1.sinks.s1.kafka.producer.max.request.size=20971520
a1.sinks.s1.kafka.producer.linger.ms=50
a1.sinks.s1.kafka.producer.acks=1
a1.sinks.s1.kafka.retries=2147483647
a1.sinks.s1.kafka.producer.request.timeout.ms=60000
a1.sinks.s1.kafka.producer.metadata.max.age.ms=600000
a1.sinks.s1.kafka.producer.max.in.flight.requests.per.connection=1
a1.sinks.s1.value.serializer = org.apache.kafka.common.serialization.StringSerializer
a1.sinks.s1.channel = c1`

**Comment by BewareMyPower** [comment]
It should be OK. You can make a test and dump the messages from topicB to verify it.
