### ISSUE TITLE
[BUG]  upgrade dependency of pulsar to enable continuous index  

### ISSUE THREAD

**Issue by aloyszhang** [streamnative/kop#289]
**Describe the bug**

Currenttly, denpendencies of pulsar are `2.8.0-rc-202012200040` which do not support continuouse index introduced by https://github.com/apache/pulsar/pull/9039.

To support this feature we should upgrade the dependencies to `2.8.0-SNPASHOT` or an alternative release version which contains the commit of https://github.com/apache/pulsar/pull/9039.

**Comment by BewareMyPower** [comment]
2.8.0-rc-202012242230
