### ISSUE TITLE
[FEATURE] does kop support __consumer_offsets topic compaction ?

### ISSUE THREAD

**Issue by WJL3333** [streamnative/kop#316]
**Is your feature request related to a problem? Please describe.**

if a large cluster or many frequent commit offset kafka clients the cost of __consumer_offsets topic loading will cost a lot. 

**Describe the solution you'd like**
want to know if __consumer_offsets support compaction and function correct

**Comment by BewareMyPower** [comment]
Currently not. If you want to support topic compaction on this topic, I think you can add an option to enable it and set `readCompacted(true)` for `GroupMetadataManager#offsetsReaders`.

**Comment by WJL3333** [comment]
thank you for your reply. this may be a useful feature for production.
