### ISSUE TITLE
[BUG] java.lang.OutOfMemoryError: unable to create new native thread when DelayedOperationPurgatory

### ISSUE THREAD

**Issue by shudo1219** [streamnative/kop#322]
**Describe the bug**
When a broker ran for 2 days, a serious OOM bug appeared as follows:
00:54:18.202 [pulsar-io-23-2] WARN  io.netty.channel.ChannelInitializer - Failed to initialize a channel. Closing: [id: 0x53537dcf, L:/ 10.39.135.14:9092 - R:/10.152.16.137:26628]
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method) ~[?:1.8.0_66]
        at java.lang.Thread.start(Thread.java:714) ~[?:1.8.0_66]
        at io.streamnative.pulsar.handlers.kop.utils.delayed.DelayedOperationPurgatory.<init>(DelayedOperationPurgatory.java:146) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.utils.delayed.DelayedOperationPurgatory$Builder.build(DelayedOperationPurgatory.java:91) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.AdminManager.<init>(AdminManager.java:49) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.KafkaRequestHandler.<init>(KafkaRequestHandler.java:179) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.KafkaChannelInitializer.initChannel(KafkaChannelInitializer.java:73) ~[?:?]
        at io.streamnative.pulsar.handlers.kop.KafkaChannelInitializer.initChannel(KafkaChannelInitializer.java:32) ~[?:?]
        at io.netty.channel.ChannelInitializer.initChannel(ChannelInitializer.java:129) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.ChannelInitializer.handlerAdded(ChannelInitializer.java:112) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannelHandlerContext.callHandlerAdded(AbstractChannelHandlerContext.java:938) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAdded0(DefaultChannelPipeline.java:609) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.access$100(DefaultChannelPipeline.java:46) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline$PendingHandlerAddedTask.execute(DefaultChannelPipeline.java:1463) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.callHandlerAddedForAllHandlers(DefaultChannelPipeline.java:1115) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.DefaultChannelPipeline.invokeHandlerAddedIfNeeded(DefaultChannelPipeline.java:650) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:502) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:417) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:474) [io.netty-netty-transport-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) [io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) [io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) [io.netty-netty-transport-native-epoll-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) [io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty-netty-common-4.1.51.Final.jar:4.1.51.Final]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]

**To Reproduce**
serveral producers continue to run for serveral days, each producer sends about 2K--5K messages per second. 
3 brokers handle 40K - 100K message per second together.

**Expected behavior**
we hope the broker process can run well especially in different and complex env.

**Screenshots**

**Additional context**

hs_err_pid365940.log:

Current thread (0x00007fe9ed5bb800):  JavaThread "ExpirationReaper-topic" [_thread_new, id=484141, stack(0x00007fe91cc96000,0x00007fe91cd97000)]

Stack: [0x00007fe91cc96000,0x00007fe91cd97000],  sp=0x00007fe91cd95740,  free space=1021k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.so+0xab9a1a]  VMError::report_and_die()+0x2ba
V  [libjvm.so+0x4f9e0b]  report_vm_out_of_memory(char const*, int, unsigned long, VMErrorType, char const*)+0x8b
V  [libjvm.so+0x91a8a3]  os::Linux::commit_memory_impl(char*, unsigned long, bool)+0x103
V  [libjvm.so+0x91a96c]  os::pd_commit_memory(char*, unsigned long, bool)+0xc
V  [libjvm.so+0x91442a]  os::commit_memory(char*, unsigned long, bool)+0x2a
V  [libjvm.so+0x918b3f]  os::pd_create_stack_guard_pages(char*, unsigned long)+0x7f
V  [libjvm.so+0xa5f6ce]  JavaThread::create_stack_guard_pages()+0x5e
V  [libjvm.so+0xa69044]  JavaThread::run()+0x34
V  [libjvm.so+0x91cc68]  java_start(Thread*)+0x108
C  [libpthread.so.0+0x7aa1]

**Comment by WJL3333** [comment]
can you show you broker config and the whole jstack？

**Comment by shudo1219** [comment]
> can you show you broker config and the whole jstack？
> And in some container environment, the max thread num can create is limited by some os parameter.
> @shudo1219

I ran the broker on a physical machine, and also modified the system config:
[root@broker1 ~]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1031766
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 655350
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 655350
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Broker config：

brokerServicePort=6650
brokerServicePortTls=
webServicePort=8080

webServicePortTls=

messagingProtocols=kafka
protocolHandlerDirectory=/usr/local/apache-pulsar-2.7.0/protocols

numIOThreads=4

numOrderedExecutorThreads=8

numHttpServerThreads=

numExecutorThreadPoolSize=

numCacheExecutorThreadPoolSize=10

maxConcurrentHttpRequests=1024

isRunningStandalone=

clusterName=pulsar-cluster

maxTenants=0

failureDomainsEnabled=false

zooKeeperSessionTimeoutMillis=30000

zooKeeperOperationTimeoutSeconds=30

zooKeeperCacheExpirySeconds=300

brokerShutdownTimeoutMs=60000

skipBrokerShutdownOnOOM=false

backlogQuotaCheckEnabled=true

backlogQuotaCheckIntervalInSeconds=60

backlogQuotaDefaultLimitGB=-1

backlogQuotaDefaultRetentionPolicy=producer_request_hold

ttlDurationDefaultInSeconds=0

allowAutoTopicCreation=true

allowAutoTopicCreationType=partitioned

allowAutoSubscriptionCreation=true

defaultNumPartitions=1

brokerDeleteInactiveTopicsEnabled=true

brokerDeleteInactiveTopicsFrequencySeconds=60

brokerDeleteInactiveTopicsMode=delete_when_no_subscriptions

brokerDeleteInactivePartitionedTopicMetadataEnabled=false

brokerDeleteInactiveTopicsMaxInactiveDurationSeconds=

maxPendingPublishdRequestsPerConnection=1000

messageExpiryCheckIntervalInMinutes=5

activeConsumerFailoverDelayTimeMillis=1000

subscriptionExpirationTimeMinutes=0

subscriptionRedeliveryTrackerEnabled=true

subscriptionExpiryCheckIntervalInMinutes=5

subscriptionKeySharedEnable=true

subscriptionKeySharedUseConsistentHashing=false

subscriptionKeySharedConsistentHashingReplicaPoints=100

brokerDeduplicationEnabled=false

brokerDeduplicationMaxNumberOfProducers=10000

brokerDeduplicationSnapshotFrequencyInSeconds=10
brokerDeduplicationSnapshotIntervalSeconds=120

brokerDeduplicationEntriesInterval=1000

brokerDeduplicationProducerInactivityTimeoutMinutes=360

defaultNumberOfNamespaceBundles=4

maxNamespacesPerTenant=0

clientLibraryVersionCheckEnabled=false

statusFilePath=

preferLaterVersions=false

maxUnackedMessagesPerConsumer=50000

maxUnackedMessagesPerSubscription=200000

maxUnackedMessagesPerBroker=0

maxUnackedMessagesPerSubscriptionOnBrokerBlocked=0.16

topicPublisherThrottlingTickTimeMillis=10

brokerPublisherThrottlingTickTimeMillis=50

brokerPublisherThrottlingMaxMessageRate=0

brokerPublisherThrottlingMaxByteRate=0

maxPublishRatePerTopicInMessages=0

maxPublishRatePerTopicInBytes=0

subscribeThrottlingRatePerConsumer=0

subscribeRatePeriodPerConsumerInSecond=30

dispatchThrottlingRatePerTopicInMsg=0

dispatchThrottlingRatePerTopicInByte=0

dispatchThrottlingRatePerSubscriptionInMsg=0

dispatchThrottlingRatePerSubscriptionInByte=0

dispatchThrottlingRatePerReplicatorInMsg=0

dispatchThrottlingRatePerReplicatorInByte=0

dispatchThrottlingRateRelativeToPublishRate=false

dispatchThrottlingOnNonBacklogConsumerEnabled=true

dispatcherMaxReadBatchSize=100

dispatcherMaxReadSizeBytes=5242880

dispatcherMinReadBatchSize=1

dispatcherMaxRoundRobinBatchSize=20

preciseDispatcherFlowControl=false

maxConcurrentLookupRequest=50000

maxConcurrentTopicLoadRequest=5000

maxConcurrentNonPersistentMessagePerConnection=1000

numWorkerThreadsForNonPersistentTopic=8

enablePersistentTopics=true

enableNonPersistentTopics=true

enableRunBookieTogether=false

enableRunBookieAutoRecoveryTogether=false

maxProducersPerTopic=0

encryptionRequireOnProducer=false

maxConsumersPerTopic=0

maxSubscriptionsPerTopic=0

maxConsumersPerSubscription=0

maxMessageSize=5242880

brokerServiceCompactionMonitorIntervalInSeconds=60

delayedDeliveryEnabled=true

delayedDeliveryTickTimeMillis=1000

acknowledgmentAtBatchIndexLevelEnabled=false

enableReplicatedSubscriptions=true

replicatedSubscriptionsSnapshotFrequencyMillis=1000

replicatedSubscriptionsSnapshotTimeoutSeconds=30

replicatedSubscriptionsSnapshotMaxCachedPerSubscription=10

maxMessagePublishBufferSizeInMB=

messagePublishBufferCheckIntervalInMillis=100

retentionCheckIntervalInSeconds=120

maxNumPartitionsPerPartitionedTopic=0

zookeeperSessionExpiredPolicy=shutdown

systemTopicEnabled=false

topicLevelPoliciesEnabled=false

topicFencingTimeoutSeconds=0

proxyRoles=

authenticateOriginalAuthData=false

tlsEnabled=false

tlsCertRefreshCheckDurationSec=300

tlsCertificateFilePath=

tlsKeyFilePath=

tlsTrustCertsFilePath=

tlsAllowInsecureConnection=false

tlsProtocols=

tlsCiphers=

tlsRequireTrustedClientCertOnConnect=false

tlsEnabledWithKeyStore=false

tlsProvider=

tlsKeyStoreType=JKS

tlsKeyStore=

tlsKeyStorePassword=

tlsTrustStoreType=JKS

tlsTrustStore=

tlsTrustStorePassword=

brokerClientTlsEnabledWithKeyStore=false

brokerClientSslProvider=

brokerClientTlsTrustStoreType=JKS

brokerClientTlsTrustStore=

brokerClientTlsTrustStorePassword=

brokerClientTlsCiphers=

brokerClientTlsProtocols=



authenticationEnabled=false

authenticationProviders=

authenticationRefreshCheckSeconds=60

authorizationEnabled=false

authorizationProvider=org.apache.pulsar.broker.authorization.PulsarAuthorizationProvider

authorizationAllowWildcardsMatching=false

superUserRoles=

brokerClientTlsEnabled=false
brokerClientAuthenticationPlugin=
brokerClientAuthenticationParameters=
brokerClientTrustCertsFilePath=

athenzDomainNames=

anonymousUserRole=


tokenSecretKey=

tokenPublicKey=

tokenAuthClaim=

tokenAudienceClaim=

tokenAudience=


saslJaasClientAllowedIds=

saslJaasBrokerSectionName=


httpMaxRequestSize=-1

httpRequestsLimitEnabled=false

httpRequestsMaxPerSecond=100.0



bookkeeperMetadataServiceUri=

bookkeeperClientAuthenticationPlugin=

bookkeeperClientAuthenticationParametersName=
bookkeeperClientAuthenticationParameters=

bookkeeperClientTimeoutInSeconds=30

bookkeeperClientSpeculativeReadTimeoutInMillis=0

bookkeeperNumberOfChannelsPerBookie=16

bookkeeperUseV2WireProtocol=true

bookkeeperClientHealthCheckEnabled=true
bookkeeperClientHealthCheckIntervalSeconds=60
bookkeeperClientHealthCheckErrorThresholdPerInterval=5
bookkeeperClientHealthCheckQuarantineTimeInSeconds=1800

bookkeeperClientQuarantineRatio=1.0

bookkeeperGetBookieInfoIntervalSeconds=86400
bookkeeperGetBookieInfoRetryIntervalSeconds=60

bookkeeperClientRackawarePolicyEnabled=true

bookkeeperClientRegionawarePolicyEnabled=false

bookkeeperClientMinNumRacksPerWriteQuorum=2

bookkeeperClientEnforceMinNumRacksPerWriteQuorum=false

bookkeeperClientReorderReadSequenceEnabled=false

bookkeeperClientIsolationGroups=

bookkeeperClientSecondaryIsolationGroups=

bookkeeperClientMinAvailableBookiesInIsolationGroups=

bookkeeperEnableStickyReads=false

bookkeeperTLSProviderFactoryClass=org.apache.bookkeeper.tls.TLSContextFactory

bookkeeperTLSClientAuthentication=false

bookkeeperTLSKeyFileType=PEM

bookkeeperTLSTrustCertTypes=PEM

bookkeeperTLSKeyStorePasswordPath=

bookkeeperTLSTrustStorePasswordPath=

bookkeeperTLSKeyFilePath=

bookkeeperTLSCertificateFilePath=

bookkeeperTLSTrustCertsFilePath=

bookkeeperDiskWeightBasedPlacementEnabled=false

bookkeeperExplicitLacIntervalInMills=0



managedLedgerDefaultEnsembleSize=2

managedLedgerDefaultWriteQuorum=2

managedLedgerDefaultAckQuorum=2

managedLedgerCursorPositionFlushSeconds = 60

managedLedgerDigestType=CRC32C

managedLedgerNumWorkerThreads=8

managedLedgerNumSchedulerThreads=8

managedLedgerCacheSizeMB=

managedLedgerCacheCopyEntries=false

managedLedgerCacheEvictionWatermark=0.9

managedLedgerCacheEvictionFrequency=100.0

managedLedgerCacheEvictionTimeThresholdMillis=1000

managedLedgerCursorBackloggedThreshold=1000

managedLedgerDefaultMarkDeleteRateLimit=1.0

managedLedgerMaxEntriesPerLedger=50000

managedLedgerMinLedgerRolloverTimeMinutes=10

managedLedgerMaxLedgerRolloverTimeMinutes=240

managedLedgerMaxSizePerLedgerMbytes=2048

managedLedgerOffloadDeletionLagMs=14400000

managedLedgerOffloadAutoTriggerSizeThresholdBytes=-1

managedLedgerCursorMaxEntriesPerLedger=50000

managedLedgerCursorRolloverTimeInSeconds=14400

managedLedgerMaxUnackedRangesToPersist=10000

managedLedgerMaxUnackedRangesToPersistInZooKeeper=1000

autoSkipNonRecoverableData=false

lazyCursorRecovery=false

managedLedgerMetadataOperationsTimeoutSeconds=60

managedLedgerReadEntryTimeoutSeconds=0

managedLedgerAddEntryTimeoutSeconds=0

managedLedgerPrometheusStatsLatencyRolloverSeconds=60

managedLedgerTraceTaskExecution=true

managedLedgerNewEntriesCheckDelayInMillis=10


loadBalancerEnabled=true

loadBalancerReportUpdateThresholdPercentage=10

loadBalancerReportUpdateMaxIntervalMinutes=15

loadBalancerHostUsageCheckIntervalMinutes=1

loadBalancerSheddingEnabled=true

loadBalancerSheddingIntervalMinutes=1

loadBalancerSheddingGracePeriodMinutes=30

loadBalancerBrokerMaxTopics=50000

loadBalancerBrokerOverloadedThresholdPercentage=85

loadBalancerResourceQuotaUpdateIntervalMinutes=15

loadBalancerAutoBundleSplitEnabled=true

loadBalancerAutoUnloadSplitBundlesEnabled=true

loadBalancerNamespaceBundleMaxTopics=1000

loadBalancerNamespaceBundleMaxSessions=1000

loadBalancerNamespaceBundleMaxMsgRate=30000

loadBalancerNamespaceBundleMaxBandwidthMbytes=100

loadBalancerNamespaceMaximumBundles=128

loadBalancerOverrideBrokerNicSpeedGbps=

loadManagerClassName=org.apache.pulsar.broker.loadbalance.impl.ModularLoadManagerImpl

supportedNamespaceBundleSplitAlgorithms=range_equally_divide,topic_count_equally_divide

defaultNamespaceBundleSplitAlgorithm=range_equally_divide

loadBalancerLoadSheddingStrategy=org.apache.pulsar.broker.loadbalance.impl.OverloadShedder

loadBalancerBrokerThresholdShedderPercentage=10

loadBalancerHistoryResourcePercentage=0.9

loadBalancerBandwithInResourceWeight=1.0

loadBalancerBandwithOutResourceWeight=1.0

loadBalancerCPUResourceWeight=1.0

loadBalancerMemoryResourceWeight=1.0

loadBalancerDirectMemoryResourceWeight=1.0

loadBalancerBundleUnloadMinThroughputThreshold=10


replicationMetricsEnabled=true

replicationConnectionsPerBroker=16

replicationProducerQueueSize=1000

replicatorPrefix=pulsar.repl

replicationPolicyCheckDurationSeconds=600

defaultRetentionTimeInMinutes=0

defaultRetentionSizeInMB=0

keepAliveIntervalSeconds=30

bootstrapNamespaces=


webSocketServiceEnabled=false

webSocketNumIoThreads=8

webSocketConnectionsPerBroker=8

webSocketSessionIdleTimeoutMillis=300000

webSocketMaxTextFrameSize=1048576


exposeTopicLevelMetricsInPrometheus=true

exposeConsumerLevelMetricsInPrometheus=false



functionsWorkerEnabled=false


exposePublisherStats=true
statsUpdateFrequencyInSecs=60
statsUpdateInitialDelayInSecs=60

exposePreciseBacklogInPrometheus=false

schemaRegistryStorageClassName=org.apache.pulsar.broker.service.schema.BookkeeperSchemaStorageFactory

isSchemaValidationEnforced=false


offloadersDirectory=./offloaders

managedLedgerOffloadDriver=

managedLedgerOffloadMaxThreads=2

managedLedgerOffloadPrefetchRounds=1

managedLedgerUnackedRangesOpenCacheSetEnabled=true

s3ManagedLedgerOffloadRegion=

s3ManagedLedgerOffloadBucket=

s3ManagedLedgerOffloadServiceEndpoint=

s3ManagedLedgerOffloadMaxBlockSizeInBytes=67108864

s3ManagedLedgerOffloadReadBufferSizeInBytes=1048576

gcsManagedLedgerOffloadRegion=

gcsManagedLedgerOffloadBucket=

gcsManagedLedgerOffloadMaxBlockSizeInBytes=67108864

gcsManagedLedgerOffloadReadBufferSizeInBytes=1048576

gcsManagedLedgerOffloadServiceAccountKeyFile=

fileSystemProfilePath=../conf/filesystem_offload_core_site.xml

fileSystemURI=


globalZookeeperServers=

replicationTlsEnabled=false

brokerServicePurgeInactiveFrequencyInSeconds=60


transactionCoordinatorEnabled=false
transactionMetadataStoreProviderClassName=org.apache.pulsar.transaction.coordinator.impl.InMemTransactionMetadataStoreProvider


@WJL3333
