### ISSUE TITLE
[BUG] Timed out MetadataRequest in flight

### ISSUE THREAD

**Issue by rodrigoreis** [streamnative/kop#407]
Timeout
When I trying to consume a message I'm getting the follow message using DotNET client.

"Timed out MetadataRequest in flight"

**%5|1616160592.294|REQTMOUT|rdkafka#producer-1| [thrd:[broker-name]:9092/bootstrap]: [broker-name]:9092/763435560: Timed out MetadataRequest in flight (after 59267ms, timeout**

[broker-name] is my broker name masked for security reasons 

**To Reproduce**
Set up brokers like described in Readme.md

**Expected behavior**
Consume messages

**Screenshots**
![image](https://user-images.githubusercontent.com/324262/111788335-bbafc100-889e-11eb-82e5-84aa006076d3.png)

**Comment by BewareMyPower** [comment]
Could you simply verify if KoP works using the official Java client like https://github.com/streamnative/kop#run-kafka-client-to-verify?

If the Java client works, there may be something wrong with the DotNET client. Please provide the version of you DotNET client and the depended librdkafka.

**Comment by BewareMyPower** [comment]
Is there any update?

**Comment by BewareMyPower** [comment]
Close this issue since there are no updates.
