### ISSUE TITLE
[BUG] Change of behavior between KoP 0.3.0 (2.6.2) and 2.7+ using SASL

### ISSUE THREAD

**Issue by jpenning-tibco** [streamnative/kop#415]
**Describe the bug**
We noticed a change in behavior between KoP 0.3.0 (2.6.2) and 2.7+ using SASL with token authentication (#206?) 

- In 0.3.0, when multiple clients connected using different SASL credentials (username=tenant/namespace) there was no cross-talk between them: Client1 with SASL1 on TopicA did not see data from Client2 with SASL2 on TopicA. 
- With 2.7.x this has changed, and Client1 and Client2 can freely exchange data.

**To Reproduce**
1. Configure Pulsar and KoP to use SASL w/ token authentication.
2. Run Kafka producers/consumers using different SASL credentials. The Kafka clients will cross-talk (Pulsar clients are not affected by this).

**Expected behavior**
The desired behavior is to have SASL credentials prevent cross-talk between Kafka clients.

**Additional context**
We understand that Kafka is not normally multi-tenant, but we think the behavior seen in 0.3.0 is very useful. We are interested to know what the intentions/goals are here. Is the behavior we rely on with 0.3.0 the intended behavior, a side-effect of the original implementation, etc?

**Comment by BewareMyPower** [comment]
I don't understand well. Could you give a more detail explanation on how two clients exchange data?

**Comment by jpenning-tibco** [comment]
> I don't understand well. Could you give a more detail explanation on how two clients exchange data?

By "two clients exchange data", I just mean messages sent by a producer app are received by a consumer app.
 
The test apps I run are basic and very similar to your Sarama/Confluent integration tests. The big difference is that my test apps have SASL configured. I can share my test apps with you if it will help.

In my test case the producer has a different SASL username and password than the consumer. In 0.3.0 if the producer app and the consumer app have different SASL username, then the consumer will not receive messages from the producer.

**Comment by jpenning-tibco** [comment]
If you need log files, config or any other data please let me know.

**Comment by BewareMyPower** [comment]
I get it. Currently the SASL/PLAIN mechanism for KoP only checks if the role has the permission for the specific namespace (username). However, the client could produce/consume to another namespace since there we have no checks for if the username that represents the namespace is what the topic belongs.

I'll take a look at how to fix it when I'm free.
