### ISSUE TITLE
[FEATURE]Can kop support low version kafka-client, such as 0.10.2

### ISSUE THREAD

**Issue by wking1986** [streamnative/kop#539]
**Is your feature request related to a problem? Please describe.**
Currently kop supports high versions of kafka, such as 1.x and 2.x, but many low versions of kafka in production environments (such as 0.10.2), and this part of users is more willing to switch pulsar

**Comment by BewareMyPower** [comment]
Currently we focused on some performance and stable issues for incoming KoP 2.8.0 (maybe a few days later), so it may be not possible to support 0.10.x.y before 2.8.0. But we'll try to support Kafka 0.10.x.y and 0.11.x.y for next releases.

**Comment by wking1986** [comment]
Thanks for your reply, after supporting 0.10.x, we are going to launch pulsar on a large scale

**Comment by zhaohaidao** [comment]
Hi, @BewareMyPower I would like to pick this up as we are use kafka-0.10.2 with a large scale, and we may start to test pulsar soon

**Comment by BewareMyPower** [comment]
@zhaohaidao Thanks for your help. FYI, after you fixed the incompatibility with Kafka 0.10.x.y client, you can add a `kafka-0-10` module just like `kafka-1-0` module to test Kafka 0.10.x.y once #605 was merged.

**Comment by BewareMyPower** [comment]
I'll assign this issue to you first @zhaohaidao

**Comment by BewareMyPower** [comment]
@zhaohaidao Hi, just to confirm that are you still working on this issue now?
