### ISSUE TITLE
[BUG] KoP cannot support a FETCH request with many partitions

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#544]
**Describe the bug**
When I run performance tests on a topic with 100 partitions, the topic will be not available quickly. What's worse is the whole KoP cluster will be broken because in this occasion, no bookie will be available. So even a new topic was created after that, it would still be unavailable because `Not enough non-faulty bookies available`.

> 15:07:19.134 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.PendingAddOp - Failed to write entry (177, 15): Bookie operation timeout
> 15:07:19.143 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Failed to find 1 bookies : excludeBookies [<Bookie:10.0.0.220:3181>, <Bookie:10.0.0.198:3181>, <Bookie:10.0.0.228:3181>], allBookies [<Bookie:10.0.0.228:3181>, <Bookie:10.0.0.198:3181>, <Bookie:10.0.0.220:3181>].
> 15:07:19.143 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Failed to choose a bookie: excluded [<Bookie:10.0.0.220:3181>, <Bookie:10.0.0.198:3181>, <Bookie:10.0.0.228:3181>], fallback to choose bookie randomly from the cluster.
> <repeated logs>...
> 15:07:19.143 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR org.apache.bookkeeper.client.MetadataUpdateLoop - UpdateLoop(ledgerId=177,loopId=4ef321e8) Exception updating
  1828 org.apache.bookkeeper.client.BKException$BKNotEnoughBookiesException: Not enough non-faulty bookies available

The root cause is `Bookie operation timeout`. It seems to lead to the result that all bookies are excluded.

After that, producer might still be enable to write some messages, but there could be a possibility that corrupted message could be written to BK, see https://github.com/streamnative/kop/issues/442 for reference. And then a direct memory leak will happen as well. https://github.com/streamnative/kop/pull/542 is to handle this corrupted messages.

When there's no connected consumer, this case won't happen.

**To Reproduce**
Deploy a KoP cluster, create 
1. Deploy a KoP cluster (maybe standalone is more easy to reproduce?)
2. Create a topic with 100 partitions
3. Run a producer and a consumer. Even if the produce rate is not so large (like 10 MB/s), the 

**Expected behavior**

**Screenshots**
Bookie operation timeout should not happen.

**Additional context**
As I debugged, it may be caused by `MessageIdUtils#getPositionForOffset`:

https://github.com/streamnative/kop/blob/f831d3777c82d0b9ee19365ed7ddd7545448185d/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/utils/MessageIdUtils.java#L96-L103

The call stacks are

```
KafkaTopicConsumerManager#remove
  KafkaTopicConsumerManager#createCursorIfNotExists
    KafkaTopicConsumerManager#getCursorByOffset
      MessageIdUtils#getPositionForOffset
```

The `getPositionForOffset` is a synchronous method that blocks until a `CompletableFuture` is completed. However, it is called in a `CompletableFuture`'s callback (`thenAccept`) when the `ManagedCursor` was not cached.

To verify the point, I added a trick fix to `getPositionForOffset`:

```java
    public static PositionImpl getPositionForOffset(ManagedLedger managedLedger, Long offset) {
        if (offset == 0L) {
            return ((ManagedLedgerImpl) managedLedger).getFirstPosition();
        }
        // ...
```

Then I succeeded testing a 100 partitions topic for a few minutes. Though, if the produce rate was too high (like 800 MB/s), after about one minute, the bug could still happen. It may be caused by a namespace unload, then `getPositionForOffset` could call `getPositionForOffset` again while offset is not zero.

Here're the logs. There's no warn/error logs in bookie.log.

[bookie.log](https://github.com/streamnative/kop/files/6586226/bookie.log)
[broker.log](https://github.com/streamnative/kop/files/6586227/broker.log)

**Comment by BewareMyPower** [comment]
FYI @dockerzhang @aloyszhang Could you reproduce this bug in your own environment?

**Comment by hangc0276** [comment]
When pub-sub with 200 partitions topic, and in catch up read case, the producer throw the following exception
```
[2021-06-03 17:02:35,972] WARN [Producer clientId=producer-1] Received invalid metadata error in produce request on partition chenhang_kop_perf_consume_v3-154 due to org.apache.kafka.common.errors.NetworkException: The server disconnected before a response was received.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)
[2021-06-03 17:02:35,972] WARN [Producer clientId=producer-1] Got error produce response with correlation id 280884 on topic-partition chenhang_kop_perf_consume_v3-3, retrying (2147483646 attempts left). Error: NETWORK_EXCEPTION (org.apache.kafka.clients.producer.internals.Sender)
```

in broker log, it creats a lot of non-durable cursor
```
pened new cursor: NonDurableCursorImpl{ledger=public/default/persistent/chenhang_kop_perf_consume_v3-partition-160, ackPos=1515:22839, readPos=1515:22840}
17:03:04.763 [pulsar-io-4-23] INFO  org.apache.bookkeeper.mledger.impl.NonDurableCursorImpl - [public/default/persistent/chenhang_kop_perf_consume_v3-partition-135] Created non-durable cursor read-position=1514:22840 mark-delete-position=1514:22839
17:03:04.763 [pulsar-io-4-23] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/chenhang_kop_perf_consume_v3-partition-135] Opened new cursor: NonDurableCursorImpl{ledger=public/default/persistent/chenhang_kop_perf_consume_v3-partition-135, ackPos=1514:22839, readPos=1514:22840}
17:03:04.796 [pulsar-io-4-23] INFO  org.apache.bookkeeper.mledger.impl.NonDurableCursorImpl - [public/default/persistent/chenhang_kop_perf_consume_v3-partition-110] Created non-durable cursor read-position=1379:22745 mark-delete-position=1379:22744
17:03:04.796 [pulsar-io-4-23] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/chenhang_kop_perf_consume_v3-partition-110] Opened new cursor: NonDurableCursorImpl{ledger=public/default/persistent/chenhang_kop_perf_consume_v3-partition-110, ackPos=1379:22744, readPos=1379:22745}
17:03:04.814 [pulsar-io-4-23] INFO  org.apache.bookkeeper.mledger.impl.NonDurableCursorImpl - [public/default/persistent/chenhang_kop_perf_consume_v3-partition-176] Created non-durable cursor read-position=1422:22715 mark-delete-position=1422:22714
```
 and with bookie timeout exception
```
17:02:36.846 [BookKeeperClientScheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.proto.PerChannelBookieClient - Timed-out 7 operations to channel [id: 0x5197bff7, L:/xxx:48434 - R:xxx/xxx:3581] for xxx:3581
17:02:36.846 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.PendingAddOp - Failed to write entry (1566, 88495): Bookie operation timeout
17:02:36.848 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Failed to choose a bookie from /default-region/default-rack : excluded [<Bookie:xxx:3581>, <Bookie:xxx:3581>], fallback to choose bookie randomly from the cluster.
17:02:36.848 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN  org.apache.bookkeeper.client.RackawareEnsem
```

**Comment by BewareMyPower** [comment]
It can be reproduced in a KoP standalone.

1. Create a topic with 100 partitions (here we use Kafka 2.7.1 because Kafka 2.0.0's admin tool must access ZK to read available brokers)

   ```bash
   ./bin/kafka-topics.sh --bootstrap-server localhost:9092 --create --topic my-topic --partitions 100 --replication-factor 1
   ```

2. Start a producer to produce messages in terminal 1

   ```bash
   ./bin/kafka-producer-perf-test.sh --topic my-topic --num-records 10000000 --throughput 5000 --record-size 1024 --topic my-topic --producer-props bootstrap.servers=localhost:9092
   ```

   The produce rate is about 4.88 MB/s.

3. Start a consumer to consume messages

   ```bash
   ./bin/kafka-consumer-perf-test.sh --bootstrap-server localhost:9092 --group my-group --topic my-topic --messages 1000000
   ```

Then the consumer cannot consume any message, the output is:

> start.time, end.time, data.consumed.in.MB, MB.sec, data.consumed.in.nMsg, nMsg.sec, rebalance.time.ms, fetch.time.ms, fetch.MB.sec, fetch.nMsg.sec
> WARNING: Exiting before consuming the expected number of messages: timeout (10000 ms) exceeded. You can use the --timeout option to increase the timeout.
> 2021-06-08 17:24:29:663, 2021-06-08 17:24:39:783, 0.0000, 0.0000, 0, 0.0000, 1623144273108, -1623144262988, -0.0000, -0.0000

Soon the producer cannot produce messages, there're a lot of logs like:

> [2021-06-08 17:25:04,020] WARN [Producer clientId=producer-1] Got error produce response with correlation id 70600 on topic-partition my-topic-70, retrying (2147483646 attempts left). Error: NETWORK_EXCEPTION (org.apache.kafka.clients.producer.internals.Sender)
>
> [2021-06-08 17:25:04,020] WARN [Producer clientId=producer-1] Received invalid metadata error in produce request on partition my-topic-70 due to org.apache.kafka.common.errors.NetworkException: The server disconnected before a response was received.. Going to request metadata update now (org.apache.kafka.clients.producer.internals.Sender)

From the KoP's logs, we can see:

> 17:25:04.772 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN org.apache.bookkeeper.client.PendingAddOp - Failed to write entry (94, 715): Bookie operation timeout
>
> 17:25:04.779 [BookKeeperClientWorker-OrderedExecutor-0-0] WARN org.apache.bookkeeper.client.RackawareEnsemblePlacementPolicyImpl - Failed to find 1 bookies : excludeBookies [<Bookie:127.0.0.1:3181>], allBookies [<Bookie:127.0.0.1:3181>].
