### ISSUE TITLE
[QUESTION] How can i query kop data by pulsar sql  ?

### ISSUE THREAD

**Issue by dik111** [streamnative/kop#550]
Hi all:
  I am new in pulsar, I test kop in pulsar stanalone , I send some data to kop test topic and I used pulsar sql to query data, but I found that the query result is not displayed normally, what should I do?

————————————————————————————————————————————————————————
Hi 各位：
  我正在用stanalone的方式测试pulsar kop，我发送一些测试的数据，然后用pulsar sql去查询数据，但是数据好像不能正常显示，我应该怎么做呢？

presto> select * from pulsar."public/default"."test";
               __value__                | __partition__ | __event_time__ |    __publish_time__     | __message_id__ | __sequence_id__ |   __producer_name__   | __key__ | __p
----------------------------------------+---------------+----------------+-------------------------+----------------+-----------------+-----------------------+---------+----
 48 65 6c 6c 6f 20 50 75 6c 73 61 72 32 |            -1 | NULL           | 2021-06-05 19:00:02.446 | (5,6,0)        |               1 | pulsar-cluster-2-19-1 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72 32 |            -1 | NULL           | 2021-06-05 19:00:02.446 | (5,7,0)        |               1 | pulsar-cluster-2-19-1 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72 33 |            -1 | NULL           | 2021-06-05 19:00:46.462 | (5,8,0)        |               0 | pulsar-cluster-2-19-2 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72 33 |            -1 | NULL           | 2021-06-05 19:00:46.462 | (5,9,0)        |               0 | pulsar-cluster-2-19-2 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72 33 |            -1 | NULL           | 2021-06-05 19:00:46.503 | (5,10,0)       |               1 | pulsar-cluster-2-19-2 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72 33 |            -1 | NULL           | 2021-06-05 19:00:46.503 | (5,11,0)       |               1 | pulsar-cluster-2-19-2 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72    |            -1 | NULL           | 2021-06-05 18:58:17.763 | (5,0,0)        |               0 | pulsar-cluster-2-19-0 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72    |            -1 | NULL           | 2021-06-05 18:58:18.124 | (5,1,0)        |               1 | pulsar-cluster-2-19-0 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72    |            -1 | NULL           | 2021-06-05 18:58:17.763 | (5,2,0)        |               0 | pulsar-cluster-2-19-0 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72    |            -1 | NULL           | 2021-06-05 18:58:18.124 | (5,3,0)        |               1 | pulsar-cluster-2-19-0 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72 32 |            -1 | NULL           | 2021-06-05 19:00:02.408 | (5,4,0)        |               0 | pulsar-cluster-2-19-1 | NULL    | {} 
 48 65 6c 6c 6f 20 50 75 6c 73 61 72 32 |            -1 | NULL           | 2021-06-05 19:00:02.408 | (5,5,0)        |               0 | pulsar-cluster-2-19-1 | NULL    | {} 
(12 rows)

Query 20210605_120849_00003_479q2, FINISHED, 1 node
Splits: 18 total, 18 done (100.00%)
0:01 [12 rows, 1.4KB] [18 rows/s, 2.21KB/s]

**Comment by gaoran10** [comment]
It seems that currently the KoP isn't supported the schema feature (@BewareMyPower please confirm), so the query result only will be bytes data.

**Comment by BewareMyPower** [comment]
Yes, KoP doesn't support schema yet. Kafka client needs Confluent Schema Registry to load/store schema.
