### ISSUE TITLE
[Question] Should it be an IllegalStateException if the group coordinator fails?

### ISSUE THREAD

**Issue by jpenning-tibco** [streamnative/kop#562]
https://github.com/streamnative/kop/blob/f357a6f1d209e3ea6416e00c354804dce003b044/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaProtocolHandler.java#L284

I ran into an issue where the group coordinator failed during a K8s deployment, leaving the broker in a bad state where producers worked but consumers did not. Deleting the pod manually and letting K8 restart the pod cleared the problem, but had the broker failed, the restart would have been automatic. Should KoP throw an IllegalStateException in this case? (This question probably applies to the transaction coordinator as well).

```
16:53:21.131 [main] ERROR io.streamnative.pulsar.handlers.kop.KafkaProtocolHandler - initGroupCoordinator failed with
org.apache.pulsar.client.admin.PulsarAdminException: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: tcm-pulsar1-broker-1.tcm-pulsar1-broker.maas-dev-tibco-tcm.svc.cluster.local
```

**Comment by BewareMyPower** [comment]
Yeah, it should. Are you willing to contribute a PR?

**Comment by jpenning-tibco** [comment]
You bet.
