### ISSUE TITLE
[QUESTION]Why operations in KOP are not asynchronously?

### ISSUE THREAD

**Issue by szknb** [streamnative/kop#590]
I think that operations in Kop are executed synchronously, such as read/write/rebalance/offset operations, because I don't see asynchronous methods related to completefuture (such as supplyasync, etc.)

My question is, since all operations are synchronized, why do we need to use **requestQueue** to correct the return order?
Here is a discussion of using requestqueue to ensure return order:https://github.com/streamnative/kop/issues/552

Thank you for your answer:)

**Comment by BewareMyPower** [comment]
The main problem is that we need to find `PersistentTopic` first using `BrokerService#getTopic`, it's an asynchronous operation.

And the most frequent requests are PRODUCE and FETCH requests, write/read operations are all asynchronous.

**Comment by szknb** [comment]
Got it, Thank you for your answer
