### ISSUE TITLE
[BUG] kafka connect distributed mode not working properly 

### ISSUE THREAD

**Issue by Krishsocgen** [streamnative/kop#606]
**Describe the bug**
I am using kop to pull the data from oracle to pulsar using kafkaconnect medium.. 

After lunching kafka connect in distributed mode I am getting kafka connect trying to connect to the coordinator but it was failing to find the coordinator 

**To Reproduce**
Kop version: 2.8.0.4 
Pulsar version : 2.8
Kafka connect : 2 and above 

Three nodes pulsar cluster .

Launch kafka connect in distributed mode by mentioning bootstrap servers 

Please enable debug in  connectlog4j.properties 

**Expected behavior**
Kafka connect will start in unstable condition 

**Screenshots**

**Additional context**

**Comment by BewareMyPower** [comment]
Could you upload your logs including both the broker's log and the kafka connect's log?

**Comment by BewareMyPower** [comment]
The cause might be that KoP somehow failed to process the `FIND_COORDINATOR` request. So the logs from broker(KoP) will be helpful for debugging.

**Comment by Krishsocgen** [comment]
Hi I am getting bellow error 
Kop version 2.8.0.4
ERROR io.streamnative.pulsar.handler.kop.utils.ZookeperUtils - Failed to create Zookeeper node /client_group_id/121.0.0.0.1-connect-1:keeper Error Code =NodeExists for /client_group_id/121.0.0.0.1-connect-1
