### ISSUE TITLE
[Enhancement] Use BrokerService instead of PulsarClient for topic lookup

### ISSUE THREAD

**Issue by BewareMyPower** [streamnative/kop#644]
**Is your feature request related to a problem? Please describe.**
Currently KoP use Pulsar broker's builtin `PulsarClient` for topic lookup, see https://github.com/streamnative/kop/blob/9630e5c0de041119ec2027502f655a3ed814f12b/kafka-impl/src/main/java/io/streamnative/pulsar/handlers/kop/KafkaTopicManager.java#L211-L212

There's a limit for this way. For example, all connections share the same `PulsarClient` instance. However, there's a pending requests limit on `PulsarClient`, i.e. if there're many connections, the load on a `PulsarClient` will be high and `TooManyRequestsException` could be thrown. There's another case that if a namespace has many topics, when a Kafka client tries to list all topics, the `TooManyRequestsException` could also be thrown because all topics need to be looked up in METADATA request handler.

**Describe the solution you'd like**
Use `BrokerService` instead of `PulsarClient` for topic lookup.

**Comment by wangjialing218** [comment]
Can we use `TopicLooupBase.lookupTopicAsync` directly to do topic lookup? We could specifiy `advertisedListenerName` to get the kafka advertised address directly, could also resolve the problem of #633

**Comment by BewareMyPower** [comment]
Yeah, I'm working on this way recently.

**Comment by BewareMyPower** [comment]
@wangjialing218 It looks like not easy to use `TopicLookupBase.lookupTopicAsync` in KoP. The broker side may send a `LookupResponse` whose `redirect` field is true to client, then Pulsar client will resend a `LookupRequest` to the redirected broker. However, there may be no way for Kafka client to do this like Pulsar client.

I'll take a further look to this problem. If you have any idea, feel free to share it.

**Comment by BewareMyPower** [comment]
After reading the source code of `NamespaceService#findBrokerServiceUrl`,  only if no one owns the bundle could the `redirect` field be set.

```java
            // First check if we or someone else already owns the bundle
            ownershipCache.getOwnerAsync(bundle).thenAccept(nsData -> {
                if (!nsData.isPresent()) {
                    // No one owns this bundle

                    if (options.isReadOnly()) {
                        // Do not attempt to acquire ownership
                        future.complete(Optional.empty());
                    } else {
                        // Now, no one owns the namespace yet. Hence, we will try to dynamically assign it
                        pulsar.getExecutor().execute(() -> {
                            searchForCandidateBroker(bundle, future, options); // NOTE: redirect is set here
                        });
                    }
```

I think we can handle the case like how we handle the `future.complete(Optional.empty())` case.
