### ISSUE TITLE
[BUG] Topic Level Permissions don't work.

### ISSUE THREAD

**Issue by ronfarkash** [streamnative/kop#675]
**Describe the bug**
Topic Level permissions don't work using KoP.

**To Reproduce**
1. Create a partitioned topic
2. Setup a JWT based authentication on broker
3. Add "produce" permissions on topic level for producer.
4. Attempt to produce messages to the created topic.

**Expected behavior**
I expect my producer to produce messages due to having specific permissions to produce to a topic.

I used KafkaJS to re-produce the bug, and permissions work when setting namespace-level permissions but not topic-level permissions.
(Works with a normal Pulsar producer).

**Comment by BewareMyPower** [comment]
KoP didn't support authorization. It just simply check the namespace level permission. But we're working on authorization currently, see https://github.com/streamnative/kop/commits/master for latest progress.

**Comment by ronfarkash** [comment]
> Now the latest master supports authorization, could you try it?

I won't be able to test it in the next few days, but I believe it didn't work since it was not implemented.

Since it got merged into the master branch I can close this issue.
