### ISSUE TITLE
[FEATURE] Can kop support setting the entry format of topic level

### ISSUE THREAD

**Issue by wenbingshen** [streamnative/kop#679]
**Is your feature request related to a problem? Please describe.**
Currently kop only supports entryFormat at the agent level. Once kop is configured with entryFormat, it will no longer be variable, and all topics will execute this entryFormat. If we want a topic to support pulsar consumption, or we want to reduce the conversion between pulsar messages and kafka messages for high-traffic topics, and hope to change the topic entryFormat to kafka, we cannot do this now except for restarting the broker.

**Describe the solution you'd like**
kop supports dynamically changing the topic-level entryFormat according to everyone’s needs.

**Comment by Demogorgon314** [comment]
Link #1581
