### ISSUE TITLE
[BUG] lombok version is too low , Compilation failed。

### ISSUE THREAD

**Issue by lordcheng10** [streamnative/kop#729]
**Describe the bug**
The lombok version is too low and does not support java10 or above, execute the command: mvn -DskipTests package, an error is reported:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pulsar-protocol-handler-kafka: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @1781a649 -> [Help 1]

Compile successfully after modifying the lombok version to 1.18.20。

**Comment by lordcheng10** [comment]
@BewareMyPower  https://github.com/streamnative/kop/pull/730

**Comment by lordcheng10** [comment]
> **Describe the bug**
> The lombok version is too low and does not support java10 or above, execute the command: mvn -DskipTests package, an error is reported:
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pulsar-protocol-handler-kafka: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @1781a649 -> [Help 1]
> 
> Compile successfully after modifying the lombok version to 1.18.20。

Switch to jdk 11 to compile successfully, it was compiled with jdk8 before。

**Comment by BewareMyPower** [comment]
So can we close this issue now?
