### ISSUE TITLE
[BUG] KoP and pulsar-2.8.0 compatibility

### ISSUE THREAD

**Issue by wenbingshen** [streamnative/kop#768]
**Describe the bug**

I use pulsar-2.8.0 and kop's current master branch to test, kafka consumers cannot consume data, kop does not throw any exceptions, and the Fetch request will never be completed until timeout, then will be cancelled; after @BewareMyPower prompt, I tested kop-2.8.0.16 and pulsar-2.8.0 also have this problem, which is a compatibility problem introduced by kop.
We should remind users about compatibility issues in this area, or we should branch out a patch for the latest kop-2.8.0.16 to solve this compatibility issue.

**Comment by BewareMyPower** [comment]
You can push a fix to branch-2.8. But since latest Pulsar 2.8.x version is 2.8.1 now, we might not release any KoP 2.8.0.x. So it's better to add docs to mark the affected minor versions.

**Comment by wenbingshen** [comment]
> You can push a fix to branch-2.8. But since latest Pulsar 2.8.x version is 2.8.1 now, we might not release any KoP 2.8.0.x in future. So it's better to add docs to mark the affected minor versions.

I agree to add docs to mark the affected minor versions.
