### ISSUE TITLE
[BUG] Kafka consumer not working - Failed to get offset

### ISSUE THREAD

**Issue by Raven888888** [streamnative/kop#789]
**Describe the bug**
Following #765 , went on to upgrade pulsar & kop from `2.7.0` to `2.8.1`, according to the [official upgrade guide](https://pulsar.apache.org/docs/en/administration-upgrade/).

Had a few strange observations after the upgrade.

1. **KafkaRequestHandler failed to get offset**
In pulsar `broker.log`:
```
11:17:51.144 [pulsar-web-40-4] INFO  org.eclipse.jetty.server.RequestLog - 192.168.3.1 - - [06/Oct/2021:11:17:51 +0000] "GET /admin/v2/persistent/public/kafka/test/partitions HTTP/1.1" 200 16 "-" "Pulsar-Java-v2.8.1" 1
11:17:51.245 [BookKeeperClientWorker-OrderedExecutor-0-0] ERROR io.streamnative.pulsar.handlers.kop.KafkaRequestHandler - [PersistentTopic{topic=persistent://public/kafka/test-partition-0}] Failed to get offset for position 7306:0
java.lang.NullPointerException: null
```
Not sure where did the position `7306` come from, could have been persisted from before the upgrade. If so, do I need to clear the `__kafka/__consumer_offsets` table after the upgrade so that kafka starts afresh?

2. **Kafka client consumer console failed to get offset**
Client version: `2.12-2.8.0`
First, get the available offsets:
`apache-kafka/bin/kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list 192.168.3.1:9092 --topic test`
got
`test:0:1088`
Then, consume at that offset:
`apache-kafka/bin/kafka-console-consumer.sh --topic test --offset 1088 --partition 0 --bootstrap-server 192.168.3.1:9092`
got error
```
[2021-10-06 17:27:58,594] WARN [Consumer clientId=consumer-console-consumer-44214-1, groupId=console-consumer-44214] Unknown server error while fetching offset 1088 for topic-partition test-0 (org.apache.kafka.clients.consumer.internals.Fetcher)
```
Since KoP server lives in pulsar broker, I tried to search in `broker.log` but did not find anything related.

3. **`__kafka` namespace topics content abnormal?**
Using pulsar sql,
.
`select * from pulsar."public/kafka"."test"; `
returns correct data exist in the table.
.
`select * from pulsar."public/__kafka"."__consumer_offsets";`
returns some rows whose `__value__` is `NULL`. Before pulsar upgrade, it used to be proper byte strings.
![image](https://user-images.githubusercontent.com/58241952/136256545-c9c1a1f6-a532-457c-8b24-167d60a278c3.png)
.
`select * from pulsar."public/__kafka"."__transaction_state";`
returns 0 rows. Is this table supposed to be empty?
.
Genuinely have no idea what happened during the upgrade.

Any help please?

**Comment by BewareMyPower** [comment]
Regarding to the first and second issues, from 2.8.0, KoP relies on the BrokerEntryMetadata feature, which adds an extra metadata part before each message. But for old messages, this part is lost. So after upgrading Pulsar/KoP to 2.8.0 or higher version, **the old messages are not accessible.**

>  If so, do I need to clear the __kafka/__consumer_offsets table after the upgrade so that kafka starts afresh?

Maybe it works. But even it works after clearing the offset topic, when KoP handles the `FETCH` request, the NPE will still happen.

Regarding to the third issue, could you try consuming the `__consumer_offsets` topic with a Pulsar consumer directly?

**Comment by Raven888888** [comment]
Thanks @BewareMyPower 

> Maybe it works. But even it works after clearing the offset topic, when KoP handles the FETCH request, the NPE will still happen.
What is your suggestion on KoP upgrade step on a production server? I could forgo the old messages prior to the upgrade, if necessary, but would like to prevent `NPE` or `FETCH` error for new data after the upgrade. Thanks.

**Comment by Raven888888** [comment]
Greetings @BewareMyPower 

Got it. I can confirmed that after removing topics in `kafka` and `__kafka` namespaces, newer 2.8.1 KoP and Kafka client work perfectly. Cheers! Closing this issue.
