### ISSUE TITLE
Support transaction producer fence

### ISSUE THREAD

**Issue by Demogorgon314** [streamnative/kop#913]
### Task list
- [ ] Upgrade Kafka dependency to 2.8.x
- [ ] Support producer fence

**Comment by BewareMyPower** [comment]
Is the dependency upgrade necessary? I found we have already cherry-picked many transaction related PRs to branch-2.8.1. I'm wondering if it could be supported with older Kafka dependency.

Or is it good to upgrade Kafka dependency of branch-2.8.1 as well?

**Comment by Demogorgon314** [comment]
> Is the dependency upgrade necessary? 

Yes, is necessary. Kafka added producer fence since 2.7.x, the Kafka client depend on `Errors.PRODUCER_FENCED`, Current KoP just return a `UNKNOWN_SERVER_ERROR`. 

> Or is it good to upgrade Kafka dependency of branch-2.8.1 as well?

Or we can just upgrade Kafka dependency in branch-2.9.x, since transaction not stable yet.

**Comment by BewareMyPower** [comment]
Got it. I think we should keep the Kafka dependency of branch-2.8.1 not changed. And the producer fence feature won't be supported for KoP 2.8.x, while the other transaction features should be supported.

**Comment by eolivelli** [comment]
First PR https://github.com/streamnative/kop/pull/1588 (still work in progress)

**Comment by eolivelli** [comment]
Related work on Kafka
https://issues.apache.org/jira/browse/KAFKA-9803
